// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MATMUL_MATMUL_Pipeline_load_A (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_TVALID,
        A_15_address0,
        A_15_ce0,
        A_15_we0,
        A_15_d0,
        A_14_address0,
        A_14_ce0,
        A_14_we0,
        A_14_d0,
        A_13_address0,
        A_13_ce0,
        A_13_we0,
        A_13_d0,
        A_12_address0,
        A_12_ce0,
        A_12_we0,
        A_12_d0,
        A_11_address0,
        A_11_ce0,
        A_11_we0,
        A_11_d0,
        A_10_address0,
        A_10_ce0,
        A_10_we0,
        A_10_d0,
        A_9_address0,
        A_9_ce0,
        A_9_we0,
        A_9_d0,
        A_8_address0,
        A_8_ce0,
        A_8_we0,
        A_8_d0,
        A_7_address0,
        A_7_ce0,
        A_7_we0,
        A_7_d0,
        A_6_address0,
        A_6_ce0,
        A_6_we0,
        A_6_d0,
        A_5_address0,
        A_5_ce0,
        A_5_we0,
        A_5_d0,
        A_4_address0,
        A_4_ce0,
        A_4_we0,
        A_4_d0,
        A_3_address0,
        A_3_ce0,
        A_3_we0,
        A_3_d0,
        A_2_address0,
        A_2_ce0,
        A_2_we0,
        A_2_d0,
        A_1_address0,
        A_1_ce0,
        A_1_we0,
        A_1_d0,
        A_address0,
        A_ce0,
        A_we0,
        A_d0,
        s_axis_TDATA,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_TVALID;
output  [3:0] A_15_address0;
output   A_15_ce0;
output   A_15_we0;
output  [31:0] A_15_d0;
output  [3:0] A_14_address0;
output   A_14_ce0;
output   A_14_we0;
output  [31:0] A_14_d0;
output  [3:0] A_13_address0;
output   A_13_ce0;
output   A_13_we0;
output  [31:0] A_13_d0;
output  [3:0] A_12_address0;
output   A_12_ce0;
output   A_12_we0;
output  [31:0] A_12_d0;
output  [3:0] A_11_address0;
output   A_11_ce0;
output   A_11_we0;
output  [31:0] A_11_d0;
output  [3:0] A_10_address0;
output   A_10_ce0;
output   A_10_we0;
output  [31:0] A_10_d0;
output  [3:0] A_9_address0;
output   A_9_ce0;
output   A_9_we0;
output  [31:0] A_9_d0;
output  [3:0] A_8_address0;
output   A_8_ce0;
output   A_8_we0;
output  [31:0] A_8_d0;
output  [3:0] A_7_address0;
output   A_7_ce0;
output   A_7_we0;
output  [31:0] A_7_d0;
output  [3:0] A_6_address0;
output   A_6_ce0;
output   A_6_we0;
output  [31:0] A_6_d0;
output  [3:0] A_5_address0;
output   A_5_ce0;
output   A_5_we0;
output  [31:0] A_5_d0;
output  [3:0] A_4_address0;
output   A_4_ce0;
output   A_4_we0;
output  [31:0] A_4_d0;
output  [3:0] A_3_address0;
output   A_3_ce0;
output   A_3_we0;
output  [31:0] A_3_d0;
output  [3:0] A_2_address0;
output   A_2_ce0;
output   A_2_we0;
output  [31:0] A_2_d0;
output  [3:0] A_1_address0;
output   A_1_ce0;
output   A_1_we0;
output  [31:0] A_1_d0;
output  [3:0] A_address0;
output   A_ce0;
output   A_we0;
output  [31:0] A_d0;
input  [511:0] s_axis_TDATA;
output   s_axis_TREADY;
input  [63:0] s_axis_TKEEP;
input  [63:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;

reg ap_idle;
reg A_15_ce0;
reg A_15_we0;
reg A_14_ce0;
reg A_14_we0;
reg A_13_ce0;
reg A_13_we0;
reg A_12_ce0;
reg A_12_we0;
reg A_11_ce0;
reg A_11_we0;
reg A_10_ce0;
reg A_10_we0;
reg A_9_ce0;
reg A_9_we0;
reg A_8_ce0;
reg A_8_we0;
reg A_7_ce0;
reg A_7_we0;
reg A_6_ce0;
reg A_6_we0;
reg A_5_ce0;
reg A_5_we0;
reg A_4_ce0;
reg A_4_we0;
reg A_3_ce0;
reg A_3_we0;
reg A_2_ce0;
reg A_2_we0;
reg A_1_ce0;
reg A_1_we0;
reg A_ce0;
reg A_we0;
reg s_axis_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln26_fu_374_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_axis_TDATA_blk_n;
wire   [63:0] zext_ln26_fu_386_p1;
reg   [4:0] i_fu_142;
wire   [4:0] add_ln26_fu_380_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_337;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

MATMUL_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_337)) begin
        if ((icmp_ln26_fu_374_p2 == 1'd0)) begin
            i_fu_142 <= add_ln26_fu_380_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_142 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_10_ce0 = 1'b1;
    end else begin
        A_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_10_we0 = 1'b1;
    end else begin
        A_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_11_ce0 = 1'b1;
    end else begin
        A_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_11_we0 = 1'b1;
    end else begin
        A_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_12_ce0 = 1'b1;
    end else begin
        A_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_12_we0 = 1'b1;
    end else begin
        A_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_13_ce0 = 1'b1;
    end else begin
        A_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_13_we0 = 1'b1;
    end else begin
        A_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_14_ce0 = 1'b1;
    end else begin
        A_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_14_we0 = 1'b1;
    end else begin
        A_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_15_ce0 = 1'b1;
    end else begin
        A_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_15_we0 = 1'b1;
    end else begin
        A_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_1_we0 = 1'b1;
    end else begin
        A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_2_ce0 = 1'b1;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_2_we0 = 1'b1;
    end else begin
        A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_3_ce0 = 1'b1;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_3_we0 = 1'b1;
    end else begin
        A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_4_ce0 = 1'b1;
    end else begin
        A_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_4_we0 = 1'b1;
    end else begin
        A_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_5_ce0 = 1'b1;
    end else begin
        A_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_5_we0 = 1'b1;
    end else begin
        A_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_6_ce0 = 1'b1;
    end else begin
        A_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_6_we0 = 1'b1;
    end else begin
        A_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_7_ce0 = 1'b1;
    end else begin
        A_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_7_we0 = 1'b1;
    end else begin
        A_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_8_ce0 = 1'b1;
    end else begin
        A_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_8_we0 = 1'b1;
    end else begin
        A_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_9_ce0 = 1'b1;
    end else begin
        A_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_9_we0 = 1'b1;
    end else begin
        A_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        A_we0 = 1'b1;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_142;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (icmp_ln26_fu_374_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_TREADY = 1'b1;
    end else begin
        s_axis_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_10_address0 = zext_ln26_fu_386_p1;

assign A_10_d0 = {{s_axis_TDATA[351:320]}};

assign A_11_address0 = zext_ln26_fu_386_p1;

assign A_11_d0 = {{s_axis_TDATA[383:352]}};

assign A_12_address0 = zext_ln26_fu_386_p1;

assign A_12_d0 = {{s_axis_TDATA[415:384]}};

assign A_13_address0 = zext_ln26_fu_386_p1;

assign A_13_d0 = {{s_axis_TDATA[447:416]}};

assign A_14_address0 = zext_ln26_fu_386_p1;

assign A_14_d0 = {{s_axis_TDATA[479:448]}};

assign A_15_address0 = zext_ln26_fu_386_p1;

assign A_15_d0 = {{s_axis_TDATA[511:480]}};

assign A_1_address0 = zext_ln26_fu_386_p1;

assign A_1_d0 = {{s_axis_TDATA[63:32]}};

assign A_2_address0 = zext_ln26_fu_386_p1;

assign A_2_d0 = {{s_axis_TDATA[95:64]}};

assign A_3_address0 = zext_ln26_fu_386_p1;

assign A_3_d0 = {{s_axis_TDATA[127:96]}};

assign A_4_address0 = zext_ln26_fu_386_p1;

assign A_4_d0 = {{s_axis_TDATA[159:128]}};

assign A_5_address0 = zext_ln26_fu_386_p1;

assign A_5_d0 = {{s_axis_TDATA[191:160]}};

assign A_6_address0 = zext_ln26_fu_386_p1;

assign A_6_d0 = {{s_axis_TDATA[223:192]}};

assign A_7_address0 = zext_ln26_fu_386_p1;

assign A_7_d0 = {{s_axis_TDATA[255:224]}};

assign A_8_address0 = zext_ln26_fu_386_p1;

assign A_8_d0 = {{s_axis_TDATA[287:256]}};

assign A_9_address0 = zext_ln26_fu_386_p1;

assign A_9_d0 = {{s_axis_TDATA[319:288]}};

assign A_address0 = zext_ln26_fu_386_p1;

assign A_d0 = s_axis_TDATA[31:0];

assign add_ln26_fu_380_p2 = (ap_sig_allocacmp_i_3 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_337 = (~((ap_start_int == 1'b0) | ((icmp_ln26_fu_374_p2 == 1'd0) & (s_axis_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln26_fu_374_p2 = ((ap_sig_allocacmp_i_3 == 5'd16) ? 1'b1 : 1'b0);

assign zext_ln26_fu_386_p1 = ap_sig_allocacmp_i_3;

endmodule //MATMUL_MATMUL_Pipeline_load_A
