// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MATMUL_MATMUL_Pipeline_store (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axis_TREADY,
        mux_case_01604_reload,
        mux_case_11606_reload,
        mux_case_21608_reload,
        mux_case_31610_reload,
        mux_case_41612_reload,
        mux_case_51614_reload,
        mux_case_61616_reload,
        mux_case_71618_reload,
        mux_case_81620_reload,
        mux_case_91622_reload,
        mux_case_101624_reload,
        mux_case_111626_reload,
        mux_case_121628_reload,
        mux_case_131630_reload,
        mux_case_141632_reload,
        mux_case_151634_reload,
        mux_case_01791636_reload,
        mux_case_11801638_reload,
        mux_case_21811640_reload,
        mux_case_31821642_reload,
        mux_case_41831644_reload,
        mux_case_51841646_reload,
        mux_case_61851648_reload,
        mux_case_71861650_reload,
        mux_case_81871652_reload,
        mux_case_91881654_reload,
        mux_case_101891656_reload,
        mux_case_111901658_reload,
        mux_case_121911660_reload,
        mux_case_131921662_reload,
        mux_case_141931664_reload,
        mux_case_151941666_reload,
        mux_case_01951668_reload,
        mux_case_11961670_reload,
        mux_case_21971672_reload,
        mux_case_31981674_reload,
        mux_case_41991676_reload,
        mux_case_52001678_reload,
        mux_case_62011680_reload,
        mux_case_72021682_reload,
        mux_case_82031684_reload,
        mux_case_92041686_reload,
        mux_case_102051688_reload,
        mux_case_112061690_reload,
        mux_case_122071692_reload,
        mux_case_132081694_reload,
        mux_case_142091696_reload,
        mux_case_152101698_reload,
        mux_case_02111700_reload,
        mux_case_12121702_reload,
        mux_case_22131704_reload,
        mux_case_32141706_reload,
        mux_case_42151708_reload,
        mux_case_52161710_reload,
        mux_case_62171712_reload,
        mux_case_72181714_reload,
        mux_case_82191716_reload,
        mux_case_92201718_reload,
        mux_case_102211720_reload,
        mux_case_112221722_reload,
        mux_case_122231724_reload,
        mux_case_132241726_reload,
        mux_case_142251728_reload,
        mux_case_152261730_reload,
        mux_case_02271732_reload,
        mux_case_12281734_reload,
        mux_case_22291736_reload,
        mux_case_32301738_reload,
        mux_case_42311740_reload,
        mux_case_52321742_reload,
        mux_case_62331744_reload,
        mux_case_72341746_reload,
        mux_case_82351748_reload,
        mux_case_92361750_reload,
        mux_case_102371752_reload,
        mux_case_112381754_reload,
        mux_case_122391756_reload,
        mux_case_132401758_reload,
        mux_case_142411760_reload,
        mux_case_152421762_reload,
        mux_case_02431764_reload,
        mux_case_12441766_reload,
        mux_case_22451768_reload,
        mux_case_32461770_reload,
        mux_case_42471772_reload,
        mux_case_52481774_reload,
        mux_case_62491776_reload,
        mux_case_72501778_reload,
        mux_case_82511780_reload,
        mux_case_92521782_reload,
        mux_case_102531784_reload,
        mux_case_112541786_reload,
        mux_case_122551788_reload,
        mux_case_132561790_reload,
        mux_case_142571792_reload,
        mux_case_152581794_reload,
        mux_case_02591796_reload,
        mux_case_12601798_reload,
        mux_case_22611800_reload,
        mux_case_32621802_reload,
        mux_case_42631804_reload,
        mux_case_52641806_reload,
        mux_case_62651808_reload,
        mux_case_72661810_reload,
        mux_case_82671812_reload,
        mux_case_92681814_reload,
        mux_case_102691816_reload,
        mux_case_112701818_reload,
        mux_case_122711820_reload,
        mux_case_132721822_reload,
        mux_case_142731824_reload,
        mux_case_152741826_reload,
        mux_case_02751828_reload,
        mux_case_12761830_reload,
        mux_case_22771832_reload,
        mux_case_32781834_reload,
        mux_case_42791836_reload,
        mux_case_52801838_reload,
        mux_case_62811840_reload,
        mux_case_72821842_reload,
        mux_case_82831844_reload,
        mux_case_92841846_reload,
        mux_case_102851848_reload,
        mux_case_112861850_reload,
        mux_case_122871852_reload,
        mux_case_132881854_reload,
        mux_case_142891856_reload,
        mux_case_152901858_reload,
        mux_case_02911860_reload,
        mux_case_12921862_reload,
        mux_case_22931864_reload,
        mux_case_32941866_reload,
        mux_case_42951868_reload,
        mux_case_52961870_reload,
        mux_case_62971872_reload,
        mux_case_72981874_reload,
        mux_case_82991876_reload,
        mux_case_93001878_reload,
        mux_case_103011880_reload,
        mux_case_113021882_reload,
        mux_case_123031884_reload,
        mux_case_133041886_reload,
        mux_case_143051888_reload,
        mux_case_153061890_reload,
        mux_case_03071892_reload,
        mux_case_13081894_reload,
        mux_case_23091896_reload,
        mux_case_33101898_reload,
        mux_case_43111900_reload,
        mux_case_53121902_reload,
        mux_case_63131904_reload,
        mux_case_73141906_reload,
        mux_case_83151908_reload,
        mux_case_93161910_reload,
        mux_case_103171912_reload,
        mux_case_113181914_reload,
        mux_case_123191916_reload,
        mux_case_133201918_reload,
        mux_case_143211920_reload,
        mux_case_153221922_reload,
        mux_case_03231924_reload,
        mux_case_13241926_reload,
        mux_case_23251928_reload,
        mux_case_33261930_reload,
        mux_case_43271932_reload,
        mux_case_53281934_reload,
        mux_case_63291936_reload,
        mux_case_73301938_reload,
        mux_case_83311940_reload,
        mux_case_93321942_reload,
        mux_case_103331944_reload,
        mux_case_113341946_reload,
        mux_case_123351948_reload,
        mux_case_133361950_reload,
        mux_case_143371952_reload,
        mux_case_153381954_reload,
        mux_case_03391956_reload,
        mux_case_13401958_reload,
        mux_case_23411960_reload,
        mux_case_33421962_reload,
        mux_case_43431964_reload,
        mux_case_53441966_reload,
        mux_case_63451968_reload,
        mux_case_73461970_reload,
        mux_case_83471972_reload,
        mux_case_93481974_reload,
        mux_case_103491976_reload,
        mux_case_113501978_reload,
        mux_case_123511980_reload,
        mux_case_133521982_reload,
        mux_case_143531984_reload,
        mux_case_153541986_reload,
        mux_case_03551988_reload,
        mux_case_13561990_reload,
        mux_case_23571992_reload,
        mux_case_33581994_reload,
        mux_case_43591996_reload,
        mux_case_53601998_reload,
        mux_case_63612000_reload,
        mux_case_73622002_reload,
        mux_case_83632004_reload,
        mux_case_93642006_reload,
        mux_case_103652008_reload,
        mux_case_113662010_reload,
        mux_case_123672012_reload,
        mux_case_133682014_reload,
        mux_case_143692016_reload,
        mux_case_153702018_reload,
        mux_case_03712020_reload,
        mux_case_13722022_reload,
        mux_case_23732024_reload,
        mux_case_33742026_reload,
        mux_case_43752028_reload,
        AB_93_load_reload,
        AB_109_load_reload,
        AB_125_load_reload,
        AB_141_load_reload,
        AB_157_load_reload,
        AB_173_load_reload,
        AB_189_load_reload,
        AB_205_load_reload,
        AB_221_load_reload,
        AB_237_load_reload,
        AB_253_load_reload,
        AB_14_load_reload,
        AB_30_load_reload,
        AB_46_load_reload,
        AB_62_load_reload,
        AB_78_load_reload,
        AB_94_load_reload,
        AB_110_load_reload,
        AB_126_load_reload,
        AB_142_load_reload,
        AB_158_load_reload,
        AB_174_load_reload,
        AB_190_load_reload,
        AB_206_load_reload,
        AB_222_load_reload,
        AB_238_load_reload,
        AB_254_load_reload,
        AB_15_load_reload,
        AB_31_load_reload,
        AB_47_load_reload,
        AB_63_load_reload,
        AB_79_load_reload,
        AB_95_load_reload,
        AB_111_load_reload,
        AB_127_load_reload,
        AB_143_load_reload,
        AB_159_load_reload,
        AB_175_load_reload,
        AB_191_load_reload,
        AB_207_load_reload,
        AB_223_load_reload,
        AB_239_load_reload,
        AB_255_load_reload,
        m_axis_TDATA,
        m_axis_TVALID,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   m_axis_TREADY;
input  [31:0] mux_case_01604_reload;
input  [31:0] mux_case_11606_reload;
input  [31:0] mux_case_21608_reload;
input  [31:0] mux_case_31610_reload;
input  [31:0] mux_case_41612_reload;
input  [31:0] mux_case_51614_reload;
input  [31:0] mux_case_61616_reload;
input  [31:0] mux_case_71618_reload;
input  [31:0] mux_case_81620_reload;
input  [31:0] mux_case_91622_reload;
input  [31:0] mux_case_101624_reload;
input  [31:0] mux_case_111626_reload;
input  [31:0] mux_case_121628_reload;
input  [31:0] mux_case_131630_reload;
input  [31:0] mux_case_141632_reload;
input  [31:0] mux_case_151634_reload;
input  [31:0] mux_case_01791636_reload;
input  [31:0] mux_case_11801638_reload;
input  [31:0] mux_case_21811640_reload;
input  [31:0] mux_case_31821642_reload;
input  [31:0] mux_case_41831644_reload;
input  [31:0] mux_case_51841646_reload;
input  [31:0] mux_case_61851648_reload;
input  [31:0] mux_case_71861650_reload;
input  [31:0] mux_case_81871652_reload;
input  [31:0] mux_case_91881654_reload;
input  [31:0] mux_case_101891656_reload;
input  [31:0] mux_case_111901658_reload;
input  [31:0] mux_case_121911660_reload;
input  [31:0] mux_case_131921662_reload;
input  [31:0] mux_case_141931664_reload;
input  [31:0] mux_case_151941666_reload;
input  [31:0] mux_case_01951668_reload;
input  [31:0] mux_case_11961670_reload;
input  [31:0] mux_case_21971672_reload;
input  [31:0] mux_case_31981674_reload;
input  [31:0] mux_case_41991676_reload;
input  [31:0] mux_case_52001678_reload;
input  [31:0] mux_case_62011680_reload;
input  [31:0] mux_case_72021682_reload;
input  [31:0] mux_case_82031684_reload;
input  [31:0] mux_case_92041686_reload;
input  [31:0] mux_case_102051688_reload;
input  [31:0] mux_case_112061690_reload;
input  [31:0] mux_case_122071692_reload;
input  [31:0] mux_case_132081694_reload;
input  [31:0] mux_case_142091696_reload;
input  [31:0] mux_case_152101698_reload;
input  [31:0] mux_case_02111700_reload;
input  [31:0] mux_case_12121702_reload;
input  [31:0] mux_case_22131704_reload;
input  [31:0] mux_case_32141706_reload;
input  [31:0] mux_case_42151708_reload;
input  [31:0] mux_case_52161710_reload;
input  [31:0] mux_case_62171712_reload;
input  [31:0] mux_case_72181714_reload;
input  [31:0] mux_case_82191716_reload;
input  [31:0] mux_case_92201718_reload;
input  [31:0] mux_case_102211720_reload;
input  [31:0] mux_case_112221722_reload;
input  [31:0] mux_case_122231724_reload;
input  [31:0] mux_case_132241726_reload;
input  [31:0] mux_case_142251728_reload;
input  [31:0] mux_case_152261730_reload;
input  [31:0] mux_case_02271732_reload;
input  [31:0] mux_case_12281734_reload;
input  [31:0] mux_case_22291736_reload;
input  [31:0] mux_case_32301738_reload;
input  [31:0] mux_case_42311740_reload;
input  [31:0] mux_case_52321742_reload;
input  [31:0] mux_case_62331744_reload;
input  [31:0] mux_case_72341746_reload;
input  [31:0] mux_case_82351748_reload;
input  [31:0] mux_case_92361750_reload;
input  [31:0] mux_case_102371752_reload;
input  [31:0] mux_case_112381754_reload;
input  [31:0] mux_case_122391756_reload;
input  [31:0] mux_case_132401758_reload;
input  [31:0] mux_case_142411760_reload;
input  [31:0] mux_case_152421762_reload;
input  [31:0] mux_case_02431764_reload;
input  [31:0] mux_case_12441766_reload;
input  [31:0] mux_case_22451768_reload;
input  [31:0] mux_case_32461770_reload;
input  [31:0] mux_case_42471772_reload;
input  [31:0] mux_case_52481774_reload;
input  [31:0] mux_case_62491776_reload;
input  [31:0] mux_case_72501778_reload;
input  [31:0] mux_case_82511780_reload;
input  [31:0] mux_case_92521782_reload;
input  [31:0] mux_case_102531784_reload;
input  [31:0] mux_case_112541786_reload;
input  [31:0] mux_case_122551788_reload;
input  [31:0] mux_case_132561790_reload;
input  [31:0] mux_case_142571792_reload;
input  [31:0] mux_case_152581794_reload;
input  [31:0] mux_case_02591796_reload;
input  [31:0] mux_case_12601798_reload;
input  [31:0] mux_case_22611800_reload;
input  [31:0] mux_case_32621802_reload;
input  [31:0] mux_case_42631804_reload;
input  [31:0] mux_case_52641806_reload;
input  [31:0] mux_case_62651808_reload;
input  [31:0] mux_case_72661810_reload;
input  [31:0] mux_case_82671812_reload;
input  [31:0] mux_case_92681814_reload;
input  [31:0] mux_case_102691816_reload;
input  [31:0] mux_case_112701818_reload;
input  [31:0] mux_case_122711820_reload;
input  [31:0] mux_case_132721822_reload;
input  [31:0] mux_case_142731824_reload;
input  [31:0] mux_case_152741826_reload;
input  [31:0] mux_case_02751828_reload;
input  [31:0] mux_case_12761830_reload;
input  [31:0] mux_case_22771832_reload;
input  [31:0] mux_case_32781834_reload;
input  [31:0] mux_case_42791836_reload;
input  [31:0] mux_case_52801838_reload;
input  [31:0] mux_case_62811840_reload;
input  [31:0] mux_case_72821842_reload;
input  [31:0] mux_case_82831844_reload;
input  [31:0] mux_case_92841846_reload;
input  [31:0] mux_case_102851848_reload;
input  [31:0] mux_case_112861850_reload;
input  [31:0] mux_case_122871852_reload;
input  [31:0] mux_case_132881854_reload;
input  [31:0] mux_case_142891856_reload;
input  [31:0] mux_case_152901858_reload;
input  [31:0] mux_case_02911860_reload;
input  [31:0] mux_case_12921862_reload;
input  [31:0] mux_case_22931864_reload;
input  [31:0] mux_case_32941866_reload;
input  [31:0] mux_case_42951868_reload;
input  [31:0] mux_case_52961870_reload;
input  [31:0] mux_case_62971872_reload;
input  [31:0] mux_case_72981874_reload;
input  [31:0] mux_case_82991876_reload;
input  [31:0] mux_case_93001878_reload;
input  [31:0] mux_case_103011880_reload;
input  [31:0] mux_case_113021882_reload;
input  [31:0] mux_case_123031884_reload;
input  [31:0] mux_case_133041886_reload;
input  [31:0] mux_case_143051888_reload;
input  [31:0] mux_case_153061890_reload;
input  [31:0] mux_case_03071892_reload;
input  [31:0] mux_case_13081894_reload;
input  [31:0] mux_case_23091896_reload;
input  [31:0] mux_case_33101898_reload;
input  [31:0] mux_case_43111900_reload;
input  [31:0] mux_case_53121902_reload;
input  [31:0] mux_case_63131904_reload;
input  [31:0] mux_case_73141906_reload;
input  [31:0] mux_case_83151908_reload;
input  [31:0] mux_case_93161910_reload;
input  [31:0] mux_case_103171912_reload;
input  [31:0] mux_case_113181914_reload;
input  [31:0] mux_case_123191916_reload;
input  [31:0] mux_case_133201918_reload;
input  [31:0] mux_case_143211920_reload;
input  [31:0] mux_case_153221922_reload;
input  [31:0] mux_case_03231924_reload;
input  [31:0] mux_case_13241926_reload;
input  [31:0] mux_case_23251928_reload;
input  [31:0] mux_case_33261930_reload;
input  [31:0] mux_case_43271932_reload;
input  [31:0] mux_case_53281934_reload;
input  [31:0] mux_case_63291936_reload;
input  [31:0] mux_case_73301938_reload;
input  [31:0] mux_case_83311940_reload;
input  [31:0] mux_case_93321942_reload;
input  [31:0] mux_case_103331944_reload;
input  [31:0] mux_case_113341946_reload;
input  [31:0] mux_case_123351948_reload;
input  [31:0] mux_case_133361950_reload;
input  [31:0] mux_case_143371952_reload;
input  [31:0] mux_case_153381954_reload;
input  [31:0] mux_case_03391956_reload;
input  [31:0] mux_case_13401958_reload;
input  [31:0] mux_case_23411960_reload;
input  [31:0] mux_case_33421962_reload;
input  [31:0] mux_case_43431964_reload;
input  [31:0] mux_case_53441966_reload;
input  [31:0] mux_case_63451968_reload;
input  [31:0] mux_case_73461970_reload;
input  [31:0] mux_case_83471972_reload;
input  [31:0] mux_case_93481974_reload;
input  [31:0] mux_case_103491976_reload;
input  [31:0] mux_case_113501978_reload;
input  [31:0] mux_case_123511980_reload;
input  [31:0] mux_case_133521982_reload;
input  [31:0] mux_case_143531984_reload;
input  [31:0] mux_case_153541986_reload;
input  [31:0] mux_case_03551988_reload;
input  [31:0] mux_case_13561990_reload;
input  [31:0] mux_case_23571992_reload;
input  [31:0] mux_case_33581994_reload;
input  [31:0] mux_case_43591996_reload;
input  [31:0] mux_case_53601998_reload;
input  [31:0] mux_case_63612000_reload;
input  [31:0] mux_case_73622002_reload;
input  [31:0] mux_case_83632004_reload;
input  [31:0] mux_case_93642006_reload;
input  [31:0] mux_case_103652008_reload;
input  [31:0] mux_case_113662010_reload;
input  [31:0] mux_case_123672012_reload;
input  [31:0] mux_case_133682014_reload;
input  [31:0] mux_case_143692016_reload;
input  [31:0] mux_case_153702018_reload;
input  [31:0] mux_case_03712020_reload;
input  [31:0] mux_case_13722022_reload;
input  [31:0] mux_case_23732024_reload;
input  [31:0] mux_case_33742026_reload;
input  [31:0] mux_case_43752028_reload;
input  [31:0] AB_93_load_reload;
input  [31:0] AB_109_load_reload;
input  [31:0] AB_125_load_reload;
input  [31:0] AB_141_load_reload;
input  [31:0] AB_157_load_reload;
input  [31:0] AB_173_load_reload;
input  [31:0] AB_189_load_reload;
input  [31:0] AB_205_load_reload;
input  [31:0] AB_221_load_reload;
input  [31:0] AB_237_load_reload;
input  [31:0] AB_253_load_reload;
input  [31:0] AB_14_load_reload;
input  [31:0] AB_30_load_reload;
input  [31:0] AB_46_load_reload;
input  [31:0] AB_62_load_reload;
input  [31:0] AB_78_load_reload;
input  [31:0] AB_94_load_reload;
input  [31:0] AB_110_load_reload;
input  [31:0] AB_126_load_reload;
input  [31:0] AB_142_load_reload;
input  [31:0] AB_158_load_reload;
input  [31:0] AB_174_load_reload;
input  [31:0] AB_190_load_reload;
input  [31:0] AB_206_load_reload;
input  [31:0] AB_222_load_reload;
input  [31:0] AB_238_load_reload;
input  [31:0] AB_254_load_reload;
input  [31:0] AB_15_load_reload;
input  [31:0] AB_31_load_reload;
input  [31:0] AB_47_load_reload;
input  [31:0] AB_63_load_reload;
input  [31:0] AB_79_load_reload;
input  [31:0] AB_95_load_reload;
input  [31:0] AB_111_load_reload;
input  [31:0] AB_127_load_reload;
input  [31:0] AB_143_load_reload;
input  [31:0] AB_159_load_reload;
input  [31:0] AB_175_load_reload;
input  [31:0] AB_191_load_reload;
input  [31:0] AB_207_load_reload;
input  [31:0] AB_223_load_reload;
input  [31:0] AB_239_load_reload;
input  [31:0] AB_255_load_reload;
output  [511:0] m_axis_TDATA;
output   m_axis_TVALID;
output  [63:0] m_axis_TKEEP;
output  [63:0] m_axis_TSTRB;
output  [0:0] m_axis_TLAST;

reg ap_idle;
reg m_axis_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_2136_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m_axis_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire   [31:0] tmp_s_fu_2152_p18;
reg   [31:0] tmp_s_reg_2802;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] tmp_1_fu_2190_p18;
reg   [31:0] tmp_1_reg_2807;
wire   [31:0] tmp_2_fu_2228_p18;
reg   [31:0] tmp_2_reg_2812;
wire   [31:0] tmp_3_fu_2266_p18;
reg   [31:0] tmp_3_reg_2817;
wire   [31:0] tmp_4_fu_2304_p18;
reg   [31:0] tmp_4_reg_2822;
wire   [31:0] tmp_5_fu_2342_p18;
reg   [31:0] tmp_5_reg_2827;
wire   [31:0] tmp_6_fu_2380_p18;
reg   [31:0] tmp_6_reg_2832;
wire   [31:0] tmp_7_fu_2418_p18;
reg   [31:0] tmp_7_reg_2837;
wire   [31:0] tmp_8_fu_2456_p18;
reg   [31:0] tmp_8_reg_2842;
wire   [31:0] tmp_9_fu_2494_p18;
reg   [31:0] tmp_9_reg_2847;
wire   [31:0] tmp_10_fu_2532_p18;
reg   [31:0] tmp_10_reg_2852;
wire   [31:0] tmp_11_fu_2570_p18;
reg   [31:0] tmp_11_reg_2857;
wire   [31:0] tmp_12_fu_2608_p18;
reg   [31:0] tmp_12_reg_2862;
wire   [31:0] tmp_13_fu_2646_p18;
reg   [31:0] tmp_13_reg_2867;
wire   [31:0] tmp_14_fu_2684_p18;
reg   [31:0] tmp_14_reg_2872;
wire   [31:0] tmp_15_fu_2722_p18;
reg   [31:0] tmp_15_reg_2877;
wire   [0:0] out_pkt_last_fu_2760_p2;
reg   [0:0] out_pkt_last_reg_2882;
reg   [4:0] i_fu_570;
wire   [4:0] add_ln59_fu_2142_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] trunc_ln61_fu_2148_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U874(
    .din0(mux_case_01604_reload),
    .din1(mux_case_11606_reload),
    .din2(mux_case_21608_reload),
    .din3(mux_case_31610_reload),
    .din4(mux_case_41612_reload),
    .din5(mux_case_51614_reload),
    .din6(mux_case_61616_reload),
    .din7(mux_case_71618_reload),
    .din8(mux_case_81620_reload),
    .din9(mux_case_91622_reload),
    .din10(mux_case_101624_reload),
    .din11(mux_case_111626_reload),
    .din12(mux_case_121628_reload),
    .din13(mux_case_131630_reload),
    .din14(mux_case_141632_reload),
    .din15(mux_case_151634_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_s_fu_2152_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U875(
    .din0(mux_case_01791636_reload),
    .din1(mux_case_11801638_reload),
    .din2(mux_case_21811640_reload),
    .din3(mux_case_31821642_reload),
    .din4(mux_case_41831644_reload),
    .din5(mux_case_51841646_reload),
    .din6(mux_case_61851648_reload),
    .din7(mux_case_71861650_reload),
    .din8(mux_case_81871652_reload),
    .din9(mux_case_91881654_reload),
    .din10(mux_case_101891656_reload),
    .din11(mux_case_111901658_reload),
    .din12(mux_case_121911660_reload),
    .din13(mux_case_131921662_reload),
    .din14(mux_case_141931664_reload),
    .din15(mux_case_151941666_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_1_fu_2190_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U876(
    .din0(mux_case_01951668_reload),
    .din1(mux_case_11961670_reload),
    .din2(mux_case_21971672_reload),
    .din3(mux_case_31981674_reload),
    .din4(mux_case_41991676_reload),
    .din5(mux_case_52001678_reload),
    .din6(mux_case_62011680_reload),
    .din7(mux_case_72021682_reload),
    .din8(mux_case_82031684_reload),
    .din9(mux_case_92041686_reload),
    .din10(mux_case_102051688_reload),
    .din11(mux_case_112061690_reload),
    .din12(mux_case_122071692_reload),
    .din13(mux_case_132081694_reload),
    .din14(mux_case_142091696_reload),
    .din15(mux_case_152101698_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_2_fu_2228_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U877(
    .din0(mux_case_02111700_reload),
    .din1(mux_case_12121702_reload),
    .din2(mux_case_22131704_reload),
    .din3(mux_case_32141706_reload),
    .din4(mux_case_42151708_reload),
    .din5(mux_case_52161710_reload),
    .din6(mux_case_62171712_reload),
    .din7(mux_case_72181714_reload),
    .din8(mux_case_82191716_reload),
    .din9(mux_case_92201718_reload),
    .din10(mux_case_102211720_reload),
    .din11(mux_case_112221722_reload),
    .din12(mux_case_122231724_reload),
    .din13(mux_case_132241726_reload),
    .din14(mux_case_142251728_reload),
    .din15(mux_case_152261730_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_3_fu_2266_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U878(
    .din0(mux_case_02271732_reload),
    .din1(mux_case_12281734_reload),
    .din2(mux_case_22291736_reload),
    .din3(mux_case_32301738_reload),
    .din4(mux_case_42311740_reload),
    .din5(mux_case_52321742_reload),
    .din6(mux_case_62331744_reload),
    .din7(mux_case_72341746_reload),
    .din8(mux_case_82351748_reload),
    .din9(mux_case_92361750_reload),
    .din10(mux_case_102371752_reload),
    .din11(mux_case_112381754_reload),
    .din12(mux_case_122391756_reload),
    .din13(mux_case_132401758_reload),
    .din14(mux_case_142411760_reload),
    .din15(mux_case_152421762_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_4_fu_2304_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U879(
    .din0(mux_case_02431764_reload),
    .din1(mux_case_12441766_reload),
    .din2(mux_case_22451768_reload),
    .din3(mux_case_32461770_reload),
    .din4(mux_case_42471772_reload),
    .din5(mux_case_52481774_reload),
    .din6(mux_case_62491776_reload),
    .din7(mux_case_72501778_reload),
    .din8(mux_case_82511780_reload),
    .din9(mux_case_92521782_reload),
    .din10(mux_case_102531784_reload),
    .din11(mux_case_112541786_reload),
    .din12(mux_case_122551788_reload),
    .din13(mux_case_132561790_reload),
    .din14(mux_case_142571792_reload),
    .din15(mux_case_152581794_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_5_fu_2342_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U880(
    .din0(mux_case_02591796_reload),
    .din1(mux_case_12601798_reload),
    .din2(mux_case_22611800_reload),
    .din3(mux_case_32621802_reload),
    .din4(mux_case_42631804_reload),
    .din5(mux_case_52641806_reload),
    .din6(mux_case_62651808_reload),
    .din7(mux_case_72661810_reload),
    .din8(mux_case_82671812_reload),
    .din9(mux_case_92681814_reload),
    .din10(mux_case_102691816_reload),
    .din11(mux_case_112701818_reload),
    .din12(mux_case_122711820_reload),
    .din13(mux_case_132721822_reload),
    .din14(mux_case_142731824_reload),
    .din15(mux_case_152741826_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_6_fu_2380_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U881(
    .din0(mux_case_02751828_reload),
    .din1(mux_case_12761830_reload),
    .din2(mux_case_22771832_reload),
    .din3(mux_case_32781834_reload),
    .din4(mux_case_42791836_reload),
    .din5(mux_case_52801838_reload),
    .din6(mux_case_62811840_reload),
    .din7(mux_case_72821842_reload),
    .din8(mux_case_82831844_reload),
    .din9(mux_case_92841846_reload),
    .din10(mux_case_102851848_reload),
    .din11(mux_case_112861850_reload),
    .din12(mux_case_122871852_reload),
    .din13(mux_case_132881854_reload),
    .din14(mux_case_142891856_reload),
    .din15(mux_case_152901858_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_7_fu_2418_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U882(
    .din0(mux_case_02911860_reload),
    .din1(mux_case_12921862_reload),
    .din2(mux_case_22931864_reload),
    .din3(mux_case_32941866_reload),
    .din4(mux_case_42951868_reload),
    .din5(mux_case_52961870_reload),
    .din6(mux_case_62971872_reload),
    .din7(mux_case_72981874_reload),
    .din8(mux_case_82991876_reload),
    .din9(mux_case_93001878_reload),
    .din10(mux_case_103011880_reload),
    .din11(mux_case_113021882_reload),
    .din12(mux_case_123031884_reload),
    .din13(mux_case_133041886_reload),
    .din14(mux_case_143051888_reload),
    .din15(mux_case_153061890_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_8_fu_2456_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U883(
    .din0(mux_case_03071892_reload),
    .din1(mux_case_13081894_reload),
    .din2(mux_case_23091896_reload),
    .din3(mux_case_33101898_reload),
    .din4(mux_case_43111900_reload),
    .din5(mux_case_53121902_reload),
    .din6(mux_case_63131904_reload),
    .din7(mux_case_73141906_reload),
    .din8(mux_case_83151908_reload),
    .din9(mux_case_93161910_reload),
    .din10(mux_case_103171912_reload),
    .din11(mux_case_113181914_reload),
    .din12(mux_case_123191916_reload),
    .din13(mux_case_133201918_reload),
    .din14(mux_case_143211920_reload),
    .din15(mux_case_153221922_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_9_fu_2494_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U884(
    .din0(mux_case_03231924_reload),
    .din1(mux_case_13241926_reload),
    .din2(mux_case_23251928_reload),
    .din3(mux_case_33261930_reload),
    .din4(mux_case_43271932_reload),
    .din5(mux_case_53281934_reload),
    .din6(mux_case_63291936_reload),
    .din7(mux_case_73301938_reload),
    .din8(mux_case_83311940_reload),
    .din9(mux_case_93321942_reload),
    .din10(mux_case_103331944_reload),
    .din11(mux_case_113341946_reload),
    .din12(mux_case_123351948_reload),
    .din13(mux_case_133361950_reload),
    .din14(mux_case_143371952_reload),
    .din15(mux_case_153381954_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_10_fu_2532_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U885(
    .din0(mux_case_03391956_reload),
    .din1(mux_case_13401958_reload),
    .din2(mux_case_23411960_reload),
    .din3(mux_case_33421962_reload),
    .din4(mux_case_43431964_reload),
    .din5(mux_case_53441966_reload),
    .din6(mux_case_63451968_reload),
    .din7(mux_case_73461970_reload),
    .din8(mux_case_83471972_reload),
    .din9(mux_case_93481974_reload),
    .din10(mux_case_103491976_reload),
    .din11(mux_case_113501978_reload),
    .din12(mux_case_123511980_reload),
    .din13(mux_case_133521982_reload),
    .din14(mux_case_143531984_reload),
    .din15(mux_case_153541986_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_11_fu_2570_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U886(
    .din0(mux_case_03551988_reload),
    .din1(mux_case_13561990_reload),
    .din2(mux_case_23571992_reload),
    .din3(mux_case_33581994_reload),
    .din4(mux_case_43591996_reload),
    .din5(mux_case_53601998_reload),
    .din6(mux_case_63612000_reload),
    .din7(mux_case_73622002_reload),
    .din8(mux_case_83632004_reload),
    .din9(mux_case_93642006_reload),
    .din10(mux_case_103652008_reload),
    .din11(mux_case_113662010_reload),
    .din12(mux_case_123672012_reload),
    .din13(mux_case_133682014_reload),
    .din14(mux_case_143692016_reload),
    .din15(mux_case_153702018_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_12_fu_2608_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U887(
    .din0(mux_case_03712020_reload),
    .din1(mux_case_13722022_reload),
    .din2(mux_case_23732024_reload),
    .din3(mux_case_33742026_reload),
    .din4(mux_case_43752028_reload),
    .din5(AB_93_load_reload),
    .din6(AB_109_load_reload),
    .din7(AB_125_load_reload),
    .din8(AB_141_load_reload),
    .din9(AB_157_load_reload),
    .din10(AB_173_load_reload),
    .din11(AB_189_load_reload),
    .din12(AB_205_load_reload),
    .din13(AB_221_load_reload),
    .din14(AB_237_load_reload),
    .din15(AB_253_load_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_13_fu_2646_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U888(
    .din0(AB_14_load_reload),
    .din1(AB_30_load_reload),
    .din2(AB_46_load_reload),
    .din3(AB_62_load_reload),
    .din4(AB_78_load_reload),
    .din5(AB_94_load_reload),
    .din6(AB_110_load_reload),
    .din7(AB_126_load_reload),
    .din8(AB_142_load_reload),
    .din9(AB_158_load_reload),
    .din10(AB_174_load_reload),
    .din11(AB_190_load_reload),
    .din12(AB_206_load_reload),
    .din13(AB_222_load_reload),
    .din14(AB_238_load_reload),
    .din15(AB_254_load_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_14_fu_2684_p18)
);

MATMUL_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U889(
    .din0(AB_15_load_reload),
    .din1(AB_31_load_reload),
    .din2(AB_47_load_reload),
    .din3(AB_63_load_reload),
    .din4(AB_79_load_reload),
    .din5(AB_95_load_reload),
    .din6(AB_111_load_reload),
    .din7(AB_127_load_reload),
    .din8(AB_143_load_reload),
    .din9(AB_159_load_reload),
    .din10(AB_175_load_reload),
    .din11(AB_191_load_reload),
    .din12(AB_207_load_reload),
    .din13(AB_223_load_reload),
    .din14(AB_239_load_reload),
    .din15(AB_255_load_reload),
    .din16(trunc_ln61_fu_2148_p1),
    .dout(tmp_15_fu_2722_p18)
);

MATMUL_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_2136_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_570 <= add_ln59_fu_2142_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_570 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_fu_2136_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_pkt_last_reg_2882 <= out_pkt_last_fu_2760_p2;
        tmp_10_reg_2852 <= tmp_10_fu_2532_p18;
        tmp_11_reg_2857 <= tmp_11_fu_2570_p18;
        tmp_12_reg_2862 <= tmp_12_fu_2608_p18;
        tmp_13_reg_2867 <= tmp_13_fu_2646_p18;
        tmp_14_reg_2872 <= tmp_14_fu_2684_p18;
        tmp_15_reg_2877 <= tmp_15_fu_2722_p18;
        tmp_1_reg_2807 <= tmp_1_fu_2190_p18;
        tmp_2_reg_2812 <= tmp_2_fu_2228_p18;
        tmp_3_reg_2817 <= tmp_3_fu_2266_p18;
        tmp_4_reg_2822 <= tmp_4_fu_2304_p18;
        tmp_5_reg_2827 <= tmp_5_fu_2342_p18;
        tmp_6_reg_2832 <= tmp_6_fu_2380_p18;
        tmp_7_reg_2837 <= tmp_7_fu_2418_p18;
        tmp_8_reg_2842 <= tmp_8_fu_2456_p18;
        tmp_9_reg_2847 <= tmp_9_fu_2494_p18;
        tmp_s_reg_2802 <= tmp_s_fu_2152_p18;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_2136_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_570;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_TDATA_blk_n = m_axis_TREADY;
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_TVALID = 1'b1;
    end else begin
        m_axis_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_fu_2142_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((m_axis_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axis_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axis_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axis_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln59_fu_2136_p2 = ((ap_sig_allocacmp_i_1 == 5'd16) ? 1'b1 : 1'b0);

assign m_axis_TDATA = {{{{{{{{{{{{{{{{tmp_15_reg_2877}, {tmp_14_reg_2872}}, {tmp_13_reg_2867}}, {tmp_12_reg_2862}}, {tmp_11_reg_2857}}, {tmp_10_reg_2852}}, {tmp_9_reg_2847}}, {tmp_8_reg_2842}}, {tmp_7_reg_2837}}, {tmp_6_reg_2832}}, {tmp_5_reg_2827}}, {tmp_4_reg_2822}}, {tmp_3_reg_2817}}, {tmp_2_reg_2812}}, {tmp_1_reg_2807}}, {tmp_s_reg_2802}};

assign m_axis_TKEEP = 64'd18446744073709551615;

assign m_axis_TLAST = out_pkt_last_reg_2882;

assign m_axis_TSTRB = 64'd0;

assign out_pkt_last_fu_2760_p2 = ((ap_sig_allocacmp_i_1 == 5'd15) ? 1'b1 : 1'b0);

assign trunc_ln61_fu_2148_p1 = ap_sig_allocacmp_i_1[3:0];

endmodule //MATMUL_MATMUL_Pipeline_store
