-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity insertion_sort_axis is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of insertion_sort_axis is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "insertion_sort_axis_insertion_sort_axis,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.700600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=349,HLS_SYN_LUT=1045,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal icmp_ln39_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_reg_389 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln39_1_fu_278_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln39_1_reg_413 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln39_fu_284_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln39_reg_418 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln39_1_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal key_fu_306_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal key_reg_443 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal arr_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal arr_ce0 : STD_LOGIC;
    signal arr_we0 : STD_LOGIC;
    signal arr_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal arr_1_ce0 : STD_LOGIC;
    signal arr_1_we0 : STD_LOGIC;
    signal arr_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal arr_2_ce0 : STD_LOGIC;
    signal arr_2_we0 : STD_LOGIC;
    signal arr_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal arr_3_ce0 : STD_LOGIC;
    signal arr_3_we0 : STD_LOGIC;
    signal arr_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal arr_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_idle : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_ready : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out_ap_vld : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out_ap_vld : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_idle : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_ready : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TREADY : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_idle : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_ready : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0 : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out_ap_vld : STD_LOGIC;
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal indvars_iv1_loc_fu_94 : STD_LOGIC_VECTOR (6 downto 0);
    signal n_loc_fu_90 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal j_loc_fu_86 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln39_fu_298_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln47_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal indvars_iv82_fu_114 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_fu_118 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln39_fu_350_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln47_fu_322_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln1_fu_288_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln47_fu_326_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln3_fu_332_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        arr_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_ce0 : OUT STD_LOGIC;
        arr_we0 : OUT STD_LOGIC;
        arr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_1_ce0 : OUT STD_LOGIC;
        arr_1_we0 : OUT STD_LOGIC;
        arr_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_2_ce0 : OUT STD_LOGIC;
        arr_2_we0 : OUT STD_LOGIC;
        arr_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_3_ce0 : OUT STD_LOGIC;
        arr_3_we0 : OUT STD_LOGIC;
        arr_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        indvars_iv1_out : OUT STD_LOGIC_VECTOR (6 downto 0);
        indvars_iv1_out_ap_vld : OUT STD_LOGIC;
        n_out : OUT STD_LOGIC_VECTOR (6 downto 0);
        n_out_ap_vld : OUT STD_LOGIC );
    end component;


    component insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        indvars_iv1_reload : IN STD_LOGIC_VECTOR (6 downto 0);
        arr_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_ce0 : OUT STD_LOGIC;
        arr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_1_ce0 : OUT STD_LOGIC;
        arr_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_2_ce0 : OUT STD_LOGIC;
        arr_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_3_ce0 : OUT STD_LOGIC;
        arr_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        n_reload : IN STD_LOGIC_VECTOR (6 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln39 : IN STD_LOGIC_VECTOR (6 downto 0);
        arr_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_ce0 : OUT STD_LOGIC;
        arr_we0 : OUT STD_LOGIC;
        arr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_1_ce0 : OUT STD_LOGIC;
        arr_1_we0 : OUT STD_LOGIC;
        arr_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_2_ce0 : OUT STD_LOGIC;
        arr_2_we0 : OUT STD_LOGIC;
        arr_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        arr_3_ce0 : OUT STD_LOGIC;
        arr_3_we0 : OUT STD_LOGIC;
        arr_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        key : IN STD_LOGIC_VECTOR (31 downto 0);
        j_out : OUT STD_LOGIC_VECTOR (6 downto 0);
        j_out_ap_vld : OUT STD_LOGIC );
    end component;


    component insertion_sort_axis_mux_4_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component insertion_sort_axis_arr_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component insertion_sort_axis_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component insertion_sort_axis_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    arr_U : component insertion_sort_axis_arr_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => arr_address0,
        ce0 => arr_ce0,
        we0 => arr_we0,
        d0 => arr_d0,
        q0 => arr_q0);

    arr_1_U : component insertion_sort_axis_arr_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => arr_1_address0,
        ce0 => arr_1_ce0,
        we0 => arr_1_we0,
        d0 => arr_1_d0,
        q0 => arr_1_q0);

    arr_2_U : component insertion_sort_axis_arr_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => arr_2_address0,
        ce0 => arr_2_ce0,
        we0 => arr_2_we0,
        d0 => arr_2_d0,
        q0 => arr_2_q0);

    arr_3_U : component insertion_sort_axis_arr_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => arr_3_address0,
        ce0 => arr_3_ce0,
        we0 => arr_3_we0,
        d0 => arr_3_d0,
        q0 => arr_3_q0);

    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198 : component insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start,
        ap_done => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done,
        ap_idle => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_idle,
        ap_ready => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        arr_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0,
        arr_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0,
        arr_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0,
        arr_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0,
        arr_1_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0,
        arr_1_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0,
        arr_1_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0,
        arr_1_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0,
        arr_2_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0,
        arr_2_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0,
        arr_2_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0,
        arr_2_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0,
        arr_3_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0,
        arr_3_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0,
        arr_3_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0,
        arr_3_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0,
        indvars_iv1_out => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out,
        indvars_iv1_out_ap_vld => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out_ap_vld,
        n_out => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out,
        n_out_ap_vld => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out_ap_vld);

    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216 : component insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start,
        ap_done => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done,
        ap_idle => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_idle,
        ap_ready => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_ready,
        out_stream_TREADY => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TREADY,
        indvars_iv1_reload => indvars_iv1_loc_fu_94,
        arr_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0,
        arr_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0,
        arr_q0 => arr_q0,
        arr_1_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0,
        arr_1_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0,
        arr_1_q0 => arr_1_q0,
        arr_2_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0,
        arr_2_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0,
        arr_2_q0 => arr_2_q0,
        arr_3_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0,
        arr_3_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0,
        arr_3_q0 => arr_3_q0,
        n_reload => n_loc_fu_90,
        out_stream_TDATA => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TDATA,
        out_stream_TVALID => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID,
        out_stream_TKEEP => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TKEEP,
        out_stream_TSTRB => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TSTRB,
        out_stream_TLAST => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TLAST);

    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234 : component insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start,
        ap_done => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done,
        ap_idle => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_idle,
        ap_ready => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_ready,
        zext_ln39 => indvars_iv82_fu_114,
        arr_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0,
        arr_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0,
        arr_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0,
        arr_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0,
        arr_q0 => arr_q0,
        arr_1_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0,
        arr_1_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0,
        arr_1_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0,
        arr_1_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0,
        arr_1_q0 => arr_1_q0,
        arr_2_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0,
        arr_2_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0,
        arr_2_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0,
        arr_2_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0,
        arr_2_q0 => arr_2_q0,
        arr_3_address0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0,
        arr_3_ce0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0,
        arr_3_we0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0,
        arr_3_d0 => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0,
        arr_3_q0 => arr_3_q0,
        key => key_reg_443,
        j_out => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out,
        j_out_ap_vld => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out_ap_vld);

    control_s_axi_U : component insertion_sort_axis_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mux_4_2_32_1_1_U31 : component insertion_sort_axis_mux_4_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => arr_q0,
        din1 => arr_1_q0,
        din2 => arr_2_q0,
        din3 => arr_3_q0,
        din4 => trunc_ln39_reg_418,
        dout => key_fu_306_p6);

    regslice_both_in_stream_V_data_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TDATA,
        vld_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TKEEP,
        vld_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TSTRB,
        vld_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component insertion_sort_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TLAST,
        vld_in => grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_ready = ap_const_logic_1)) then 
                    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_ready = ap_const_logic_1)) then 
                    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln39_1_fu_273_p2 = ap_const_lv1_1) or (icmp_ln39_reg_389 = ap_const_lv1_1)))) then 
                    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_ready = ap_const_logic_1)) then 
                    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_254_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_fu_118 <= ap_const_lv7_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                i_fu_118 <= add_ln39_fu_350_p2;
            end if; 
        end if;
    end process;

    indvars_iv82_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_254_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                indvars_iv82_fu_114 <= ap_const_lv7_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                indvars_iv82_fu_114 <= add_ln39_1_reg_413;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                add_ln39_1_reg_413 <= add_ln39_1_fu_278_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln39_reg_389 <= icmp_ln39_fu_254_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out_ap_vld = ap_const_logic_1))) then
                indvars_iv1_loc_fu_94 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                j_loc_fu_86 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                key_reg_443 <= key_fu_306_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out_ap_vld = ap_const_logic_1))) then
                n_loc_fu_90 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                trunc_ln39_reg_418 <= trunc_ln39_fu_284_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state11, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln39_1_fu_273_p2 = ap_const_lv1_1) or (icmp_ln39_reg_389 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    add_ln39_1_fu_278_p2 <= std_logic_vector(unsigned(indvars_iv82_fu_114) + unsigned(ap_const_lv7_1));
    add_ln39_fu_350_p2 <= std_logic_vector(unsigned(i_fu_118) + unsigned(ap_const_lv7_1));
    add_ln47_fu_326_p2 <= std_logic_vector(unsigned(j_loc_fu_86) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done)
    begin
        if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done)
    begin
        if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done)
    begin
        if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state11, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    arr_1_address0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, zext_ln39_fu_298_p1, zext_ln47_fu_342_p1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_1_address0 <= zext_ln47_fu_342_p1(5 - 1 downto 0);
        elsif (((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            arr_1_address0 <= zext_ln39_fu_298_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_1_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_1_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_1_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0;
        else 
            arr_1_address0 <= "XXXXX";
        end if; 
    end process;


    arr_1_ce0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            arr_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_1_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_1_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_1_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0;
        else 
            arr_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_1_d0_assign_proc : process(key_reg_443, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_1_d0 <= key_reg_443;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_1_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_1_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0;
        else 
            arr_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    arr_1_we0_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9, trunc_ln47_fu_322_p1)
    begin
        if (((trunc_ln47_fu_322_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            arr_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_1_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_1_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0;
        else 
            arr_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_2_address0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, zext_ln39_fu_298_p1, zext_ln47_fu_342_p1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_2_address0 <= zext_ln47_fu_342_p1(5 - 1 downto 0);
        elsif (((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            arr_2_address0 <= zext_ln39_fu_298_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_2_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_2_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_2_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0;
        else 
            arr_2_address0 <= "XXXXX";
        end if; 
    end process;


    arr_2_ce0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            arr_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_2_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_2_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_2_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0;
        else 
            arr_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_2_d0_assign_proc : process(key_reg_443, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_2_d0 <= key_reg_443;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_2_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_2_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0;
        else 
            arr_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    arr_2_we0_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9, trunc_ln47_fu_322_p1)
    begin
        if (((trunc_ln47_fu_322_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            arr_2_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_2_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_2_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0;
        else 
            arr_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_3_address0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, zext_ln39_fu_298_p1, zext_ln47_fu_342_p1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_3_address0 <= zext_ln47_fu_342_p1(5 - 1 downto 0);
        elsif (((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            arr_3_address0 <= zext_ln39_fu_298_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_3_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_3_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_3_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0;
        else 
            arr_3_address0 <= "XXXXX";
        end if; 
    end process;


    arr_3_ce0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            arr_3_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_3_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_3_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_3_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0;
        else 
            arr_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_3_d0_assign_proc : process(key_reg_443, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_3_d0 <= key_reg_443;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_3_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_3_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0;
        else 
            arr_3_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    arr_3_we0_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9, trunc_ln47_fu_322_p1)
    begin
        if (((trunc_ln47_fu_322_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            arr_3_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_3_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_3_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0;
        else 
            arr_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_address0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, zext_ln39_fu_298_p1, zext_ln47_fu_342_p1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_address0 <= zext_ln47_fu_342_p1(5 - 1 downto 0);
        elsif (((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            arr_address0 <= zext_ln39_fu_298_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_address0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0;
        else 
            arr_address0 <= "XXXXX";
        end if; 
    end process;


    arr_ce0_assign_proc : process(icmp_ln39_reg_389, ap_CS_fsm_state5, icmp_ln39_1_fu_273_p2, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln39_1_fu_273_p2 = ap_const_lv1_0) and (icmp_ln39_reg_389 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            arr_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            arr_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_ce0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0;
        else 
            arr_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_d0_assign_proc : process(key_reg_443, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            arr_d0 <= key_reg_443;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_d0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0;
        else 
            arr_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    arr_we0_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0, grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0, ap_CS_fsm_state3, ap_CS_fsm_state8, ap_CS_fsm_state9, trunc_ln47_fu_322_p1)
    begin
        if (((trunc_ln47_fu_322_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            arr_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            arr_we0 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0;
        else 
            arr_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg;
    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg;
    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg;
    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state10);
    icmp_ln39_1_fu_273_p2 <= "1" when (indvars_iv82_fu_114 = n_loc_fu_90) else "0";
    icmp_ln39_fu_254_p2 <= "1" when (n_loc_fu_90 = ap_const_lv7_0) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln1_fu_288_p4 <= i_fu_118(6 downto 2);
    lshr_ln3_fu_332_p4 <= add_ln47_fu_326_p2(6 downto 2);
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID;
    trunc_ln39_fu_284_p1 <= i_fu_118(2 - 1 downto 0);
    trunc_ln47_fu_322_p1 <= j_loc_fu_86(2 - 1 downto 0);
    zext_ln39_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_288_p4),64));
    zext_ln47_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_fu_332_p4),64));
end behav;
