-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln39 : IN STD_LOGIC_VECTOR (6 downto 0);
    arr_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_ce0 : OUT STD_LOGIC;
    arr_we0 : OUT STD_LOGIC;
    arr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arr_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_1_ce0 : OUT STD_LOGIC;
    arr_1_we0 : OUT STD_LOGIC;
    arr_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arr_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_2_ce0 : OUT STD_LOGIC;
    arr_2_we0 : OUT STD_LOGIC;
    arr_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arr_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_3_ce0 : OUT STD_LOGIC;
    arr_3_we0 : OUT STD_LOGIC;
    arr_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    key : IN STD_LOGIC_VECTOR (31 downto 0);
    j_out : OUT STD_LOGIC_VECTOR (6 downto 0);
    j_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal j_1_reg_276 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_fu_179_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_reg_282 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_reg_288 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_19_fu_209_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_19_reg_312 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_fu_212_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_316 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln43_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_324 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln41_fu_201_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_fu_246_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal j_fu_60 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln45_fu_254_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln39_cast_fu_167_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal lshr_ln2_fu_191_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_212_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln44_fu_231_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln5_fu_236_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component insertion_sort_axis_mux_4_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mux_4_2_32_1_1_U11 : component insertion_sort_axis_mux_4_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => arr_q0,
        din1 => arr_1_q0,
        din2 => arr_2_q0,
        din3 => arr_3_q0,
        din4 => tmp_fu_212_p5,
        dout => tmp_fu_212_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    j_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                j_fu_60 <= zext_ln39_cast_fu_167_p1;
            elsif (((icmp_ln43_reg_324 = ap_const_lv1_1) and (tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_fu_60 <= add_ln45_fu_254_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                empty_19_reg_312 <= empty_19_fu_209_p1;
                icmp_ln43_reg_324 <= icmp_ln43_fu_226_p2;
                tmp_reg_316 <= tmp_fu_212_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                empty_reg_282 <= empty_fu_179_p1;
                j_1_reg_276 <= j_fu_60;
                tmp_1_reg_288 <= j_fu_60(7 downto 7);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_1_reg_288, ap_CS_fsm_state3, icmp_ln43_fu_226_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln43_fu_226_p2 = ap_const_lv1_1) and (tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((tmp_1_reg_288 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln44_fu_231_p2 <= std_logic_vector(unsigned(empty_reg_282) + unsigned(ap_const_lv7_1));
    add_ln45_fu_254_p2 <= std_logic_vector(unsigned(j_1_reg_276) + unsigned(ap_const_lv8_FF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    arr_1_address0_assign_proc : process(ap_CS_fsm_state2, zext_ln41_fu_201_p1, zext_ln44_fu_246_p1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            arr_1_address0 <= zext_ln44_fu_246_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arr_1_address0 <= zext_ln41_fu_201_p1(5 - 1 downto 0);
        else 
            arr_1_address0 <= "XXXXX";
        end if; 
    end process;


    arr_1_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_1_ce0 <= ap_const_logic_1;
        else 
            arr_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_1_d0 <= tmp_reg_316;

    arr_1_we0_assign_proc : process(tmp_1_reg_288, empty_19_reg_312, icmp_ln43_reg_324, ap_CS_fsm_state4)
    begin
        if (((icmp_ln43_reg_324 = ap_const_lv1_1) and (empty_19_reg_312 = ap_const_lv2_0) and (tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_1_we0 <= ap_const_logic_1;
        else 
            arr_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_2_address0_assign_proc : process(ap_CS_fsm_state2, zext_ln41_fu_201_p1, zext_ln44_fu_246_p1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            arr_2_address0 <= zext_ln44_fu_246_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arr_2_address0 <= zext_ln41_fu_201_p1(5 - 1 downto 0);
        else 
            arr_2_address0 <= "XXXXX";
        end if; 
    end process;


    arr_2_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_2_ce0 <= ap_const_logic_1;
        else 
            arr_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_2_d0 <= tmp_reg_316;

    arr_2_we0_assign_proc : process(tmp_1_reg_288, empty_19_reg_312, icmp_ln43_reg_324, ap_CS_fsm_state4)
    begin
        if (((icmp_ln43_reg_324 = ap_const_lv1_1) and (empty_19_reg_312 = ap_const_lv2_1) and (tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_2_we0 <= ap_const_logic_1;
        else 
            arr_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_3_address0_assign_proc : process(ap_CS_fsm_state2, zext_ln41_fu_201_p1, zext_ln44_fu_246_p1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            arr_3_address0 <= zext_ln44_fu_246_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arr_3_address0 <= zext_ln41_fu_201_p1(5 - 1 downto 0);
        else 
            arr_3_address0 <= "XXXXX";
        end if; 
    end process;


    arr_3_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_3_ce0 <= ap_const_logic_1;
        else 
            arr_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_3_d0 <= tmp_reg_316;

    arr_3_we0_assign_proc : process(tmp_1_reg_288, empty_19_reg_312, icmp_ln43_reg_324, ap_CS_fsm_state4)
    begin
        if (((icmp_ln43_reg_324 = ap_const_lv1_1) and (empty_19_reg_312 = ap_const_lv2_2) and (tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_3_we0 <= ap_const_logic_1;
        else 
            arr_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr_address0_assign_proc : process(ap_CS_fsm_state2, zext_ln41_fu_201_p1, zext_ln44_fu_246_p1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            arr_address0 <= zext_ln44_fu_246_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            arr_address0 <= zext_ln41_fu_201_p1(5 - 1 downto 0);
        else 
            arr_address0 <= "XXXXX";
        end if; 
    end process;


    arr_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_ce0 <= ap_const_logic_1;
        else 
            arr_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_d0 <= tmp_reg_316;

    arr_we0_assign_proc : process(tmp_1_reg_288, empty_19_reg_312, icmp_ln43_reg_324, ap_CS_fsm_state4)
    begin
        if (((icmp_ln43_reg_324 = ap_const_lv1_1) and (empty_19_reg_312 = ap_const_lv2_3) and (tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            arr_we0 <= ap_const_logic_1;
        else 
            arr_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_19_fu_209_p1 <= j_1_reg_276(2 - 1 downto 0);
    empty_fu_179_p1 <= j_fu_60(7 - 1 downto 0);
    icmp_ln43_fu_226_p2 <= "1" when (signed(tmp_fu_212_p6) > signed(key)) else "0";
    j_out <= empty_reg_282;

    j_out_ap_vld_assign_proc : process(tmp_1_reg_288, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((tmp_1_reg_288 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            j_out_ap_vld <= ap_const_logic_1;
        else 
            j_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln2_fu_191_p4 <= j_fu_60(6 downto 2);
    lshr_ln5_fu_236_p4 <= add_ln44_fu_231_p2(6 downto 2);
    tmp_fu_212_p5 <= j_1_reg_276(2 - 1 downto 0);
    zext_ln39_cast_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln39),8));
    zext_ln41_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_191_p4),64));
    zext_ln44_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_fu_236_p4),64));
end behav;
