-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity alu_led is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    sw : IN STD_LOGIC_VECTOR (7 downto 0);
    led : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of alu_led is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "alu_led_alu_led,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.473900,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=69,HLS_SYN_LUT=147,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

    signal num1_fu_78_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal num1_reg_172 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal num2_fu_82_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal num2_reg_180 : STD_LOGIC_VECTOR (2 downto 0);
    signal opcode_fu_92_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal opcode_reg_188 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln25_fu_102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_192 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln11_1_fu_126_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln11_fu_142_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln11_fu_158_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_mux_result_1_phi_fu_65_p10 : STD_LOGIC_VECTOR (6 downto 0);
    signal result_1_reg_61 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln11_2_fu_162_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_108_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_108_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal result_3_fu_120_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal result_3_fu_120_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal result_3_fu_120_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln19_fu_130_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln19_1_fu_133_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal result_2_fu_136_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln16_1_fu_149_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln16_fu_146_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal result_fu_152_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_108_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_108_ap_start : STD_LOGIC;
    signal grp_fu_108_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal result_3_fu_120_p00 : STD_LOGIC_VECTOR (5 downto 0);
    signal result_3_fu_120_p10 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component alu_led_udiv_3ns_3ns_3_7_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component alu_led_mul_3ns_3ns_6_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;



begin
    udiv_3ns_3ns_3_7_seq_1_U1 : component alu_led_udiv_3ns_3ns_3_7_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_108_ap_start,
        done => grp_fu_108_ap_done,
        din0 => grp_fu_108_p0,
        din1 => grp_fu_108_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_108_p2);

    mul_3ns_3ns_6_1_1_U2 : component alu_led_mul_3ns_3ns_6_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        dout_WIDTH => 6)
    port map (
        din0 => result_3_fu_120_p0,
        din1 => result_3_fu_120_p1,
        dout => result_3_fu_120_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    result_1_reg_61_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln25_fu_102_p2 = ap_const_lv1_1) and (opcode_fu_92_p4 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                result_1_reg_61 <= ap_const_lv7_0;
            elsif (((icmp_ln25_reg_192 = ap_const_lv1_0) and (opcode_reg_188 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                result_1_reg_61 <= zext_ln11_2_fu_162_p1;
            elsif (((opcode_reg_188 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                result_1_reg_61 <= zext_ln11_fu_158_p1;
            elsif (((opcode_reg_188 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                result_1_reg_61 <= sext_ln11_fu_142_p1;
            elsif (((opcode_reg_188 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                result_1_reg_61 <= zext_ln11_1_fu_126_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((opcode_fu_92_p4 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln25_reg_192 <= icmp_ln25_fu_102_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                num1_reg_172 <= num1_fu_78_p1;
                num2_reg_180 <= sw(5 downto 3);
                opcode_reg_188 <= sw(7 downto 6);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, opcode_fu_92_p4, icmp_ln25_fu_102_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln25_fu_102_p2 = ap_const_lv1_1) and (opcode_fu_92_p4 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((icmp_ln25_fu_102_p2 = ap_const_lv1_0) and (opcode_fu_92_p4 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_phi_mux_result_1_phi_fu_65_p10_assign_proc : process(opcode_reg_188, icmp_ln25_reg_192, result_1_reg_61, zext_ln11_2_fu_162_p1, ap_CS_fsm_state8)
    begin
        if (((icmp_ln25_reg_192 = ap_const_lv1_0) and (opcode_reg_188 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_phi_mux_result_1_phi_fu_65_p10 <= zext_ln11_2_fu_162_p1;
        else 
            ap_phi_mux_result_1_phi_fu_65_p10 <= result_1_reg_61;
        end if; 
    end process;


    grp_fu_108_ap_start_assign_proc : process(ap_CS_fsm_state1, opcode_fu_92_p4, icmp_ln25_fu_102_p2)
    begin
        if (((icmp_ln25_fu_102_p2 = ap_const_lv1_0) and (opcode_fu_92_p4 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_fu_108_ap_start <= ap_const_logic_1;
        else 
            grp_fu_108_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_108_p0 <= sw(3 - 1 downto 0);
    grp_fu_108_p1 <= sw(5 downto 3);
    icmp_ln25_fu_102_p2 <= "1" when (num2_fu_82_p4 = ap_const_lv3_0) else "0";
        led <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_mux_result_1_phi_fu_65_p10),8));

    num1_fu_78_p1 <= sw(3 - 1 downto 0);
    num2_fu_82_p4 <= sw(5 downto 3);
    opcode_fu_92_p4 <= sw(7 downto 6);
    result_2_fu_136_p2 <= std_logic_vector(unsigned(zext_ln19_fu_130_p1) - unsigned(zext_ln19_1_fu_133_p1));
    result_3_fu_120_p0 <= result_3_fu_120_p00(3 - 1 downto 0);
    result_3_fu_120_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num2_reg_180),6));
    result_3_fu_120_p1 <= result_3_fu_120_p10(3 - 1 downto 0);
    result_3_fu_120_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num1_reg_172),6));
    result_fu_152_p2 <= std_logic_vector(unsigned(zext_ln16_1_fu_149_p1) + unsigned(zext_ln16_fu_146_p1));
        sext_ln11_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(result_2_fu_136_p2),7));

    zext_ln11_1_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_3_fu_120_p2),7));
    zext_ln11_2_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_108_p2),7));
    zext_ln11_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_fu_152_p2),7));
    zext_ln16_1_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num2_reg_180),4));
    zext_ln16_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num1_reg_172),4));
    zext_ln19_1_fu_133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num2_reg_180),4));
    zext_ln19_fu_130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(num1_reg_172),4));
end behav;
