// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        arr_address0,
        arr_ce0,
        arr_we0,
        arr_d0,
        arr_1_address0,
        arr_1_ce0,
        arr_1_we0,
        arr_1_d0,
        arr_2_address0,
        arr_2_ce0,
        arr_2_we0,
        arr_2_d0,
        arr_3_address0,
        arr_3_ce0,
        arr_3_we0,
        arr_3_d0,
        indvars_iv1_out,
        indvars_iv1_out_ap_vld,
        n_out,
        n_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [4:0] arr_address0;
output   arr_ce0;
output   arr_we0;
output  [31:0] arr_d0;
output  [4:0] arr_1_address0;
output   arr_1_ce0;
output   arr_1_we0;
output  [31:0] arr_1_d0;
output  [4:0] arr_2_address0;
output   arr_2_ce0;
output   arr_2_we0;
output  [31:0] arr_2_d0;
output  [4:0] arr_3_address0;
output   arr_3_ce0;
output   arr_3_we0;
output  [31:0] arr_3_d0;
output  [6:0] indvars_iv1_out;
output   indvars_iv1_out_ap_vld;
output  [6:0] n_out;
output   n_out_ap_vld;

reg ap_idle;
reg in_stream_TREADY;
reg arr_ce0;
reg arr_we0;
reg arr_1_ce0;
reg arr_1_we0;
reg arr_2_ce0;
reg arr_2_we0;
reg arr_3_ce0;
reg arr_3_we0;
reg indvars_iv1_out_ap_vld;
reg n_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] and_ln34_fu_226_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
reg   [6:0] indvars_iv1_reg_152;
reg   [6:0] n_reg_163;
wire   [6:0] add_ln33_fu_208_p2;
wire   [6:0] add_ln34_fu_232_p2;
reg   [6:0] ap_phi_mux_indvars_iv1_phi_fu_155_p4;
wire    ap_loop_init;
reg   [6:0] ap_phi_mux_n_phi_fu_166_p4;
wire   [63:0] zext_ln24_fu_188_p1;
wire   [1:0] empty_fu_174_p1;
wire   [4:0] lshr_ln_fu_178_p4;
wire   [0:0] icmp_ln34_fu_220_p2;
wire   [0:0] xor_ln34_fu_214_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

insertion_sort_axis_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'd1 == and_ln34_fu_226_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        indvars_iv1_reg_152 <= add_ln34_fu_232_p2;
        n_reg_163 <= add_ln33_fu_208_p2;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'd0 == and_ln34_fu_226_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_indvars_iv1_phi_fu_155_p4 = 7'd1;
    end else begin
        ap_phi_mux_indvars_iv1_phi_fu_155_p4 = indvars_iv1_reg_152;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_n_phi_fu_166_p4 = 7'd0;
    end else begin
        ap_phi_mux_n_phi_fu_166_p4 = n_reg_163;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        arr_1_ce0 = 1'b1;
    end else begin
        arr_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (empty_fu_174_p1 == 2'd1))) begin
        arr_1_we0 = 1'b1;
    end else begin
        arr_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        arr_2_ce0 = 1'b1;
    end else begin
        arr_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (empty_fu_174_p1 == 2'd2))) begin
        arr_2_we0 = 1'b1;
    end else begin
        arr_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        arr_3_ce0 = 1'b1;
    end else begin
        arr_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (empty_fu_174_p1 == 2'd3))) begin
        arr_3_we0 = 1'b1;
    end else begin
        arr_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        arr_ce0 = 1'b1;
    end else begin
        arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (empty_fu_174_p1 == 2'd0))) begin
        arr_we0 = 1'b1;
    end else begin
        arr_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'd0 == and_ln34_fu_226_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        indvars_iv1_out_ap_vld = 1'b1;
    end else begin
        indvars_iv1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0)) & (1'd0 == and_ln34_fu_226_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        n_out_ap_vld = 1'b1;
    end else begin
        n_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln33_fu_208_p2 = (ap_phi_mux_n_phi_fu_166_p4 + 7'd1);

assign add_ln34_fu_232_p2 = (ap_phi_mux_indvars_iv1_phi_fu_155_p4 + 7'd1);

assign and_ln34_fu_226_p2 = (xor_ln34_fu_214_p2 & icmp_ln34_fu_220_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((in_stream_TVALID == 1'b0) | (ap_start_int == 1'b0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign arr_1_address0 = zext_ln24_fu_188_p1;

assign arr_1_d0 = in_stream_TDATA;

assign arr_2_address0 = zext_ln24_fu_188_p1;

assign arr_2_d0 = in_stream_TDATA;

assign arr_3_address0 = zext_ln24_fu_188_p1;

assign arr_3_d0 = in_stream_TDATA;

assign arr_address0 = zext_ln24_fu_188_p1;

assign arr_d0 = in_stream_TDATA;

assign empty_fu_174_p1 = ap_phi_mux_n_phi_fu_166_p4[1:0];

assign icmp_ln34_fu_220_p2 = ((add_ln33_fu_208_p2 < 7'd100) ? 1'b1 : 1'b0);

assign indvars_iv1_out = ap_phi_mux_indvars_iv1_phi_fu_155_p4;

assign lshr_ln_fu_178_p4 = {{ap_phi_mux_n_phi_fu_166_p4[6:2]}};

assign n_out = ap_phi_mux_n_phi_fu_166_p4;

assign xor_ln34_fu_214_p2 = (in_stream_TLAST ^ 1'd1);

assign zext_ln24_fu_188_p1 = lshr_ln_fu_178_p4;

endmodule //insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1
