-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    arr_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_ce0 : OUT STD_LOGIC;
    arr_we0 : OUT STD_LOGIC;
    arr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_1_ce0 : OUT STD_LOGIC;
    arr_1_we0 : OUT STD_LOGIC;
    arr_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_2_ce0 : OUT STD_LOGIC;
    arr_2_we0 : OUT STD_LOGIC;
    arr_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr_3_ce0 : OUT STD_LOGIC;
    arr_3_we0 : OUT STD_LOGIC;
    arr_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    indvars_iv1_out : OUT STD_LOGIC_VECTOR (6 downto 0);
    indvars_iv1_out_ap_vld : OUT STD_LOGIC;
    n_out : OUT STD_LOGIC_VECTOR (6 downto 0);
    n_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_64 : STD_LOGIC_VECTOR (6 downto 0) := "1100100";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal and_ln34_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal indvars_iv1_reg_152 : STD_LOGIC_VECTOR (6 downto 0);
    signal n_reg_163 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln33_fu_208_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln34_fu_232_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_mux_indvars_iv1_phi_fu_155_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_n_phi_fu_166_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln24_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_174_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal lshr_ln_fu_178_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln34_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln34_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component insertion_sort_axis_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component insertion_sort_axis_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln34_fu_226_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                indvars_iv1_reg_152 <= add_ln34_fu_232_p2;
                n_reg_163 <= add_ln33_fu_208_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln33_fu_208_p2 <= std_logic_vector(unsigned(ap_phi_mux_n_phi_fu_166_p4) + unsigned(ap_const_lv7_1));
    add_ln34_fu_232_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvars_iv1_phi_fu_155_p4) + unsigned(ap_const_lv7_1));
    and_ln34_fu_226_p2 <= (xor_ln34_fu_214_p2 and icmp_ln34_fu_220_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(in_stream_TVALID, ap_start_int)
    begin
        if (((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, and_ln34_fu_226_p2, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_lv1_0 = and_ln34_fu_226_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_indvars_iv1_phi_fu_155_p4_assign_proc : process(ap_CS_fsm_state1, indvars_iv1_reg_152, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_indvars_iv1_phi_fu_155_p4 <= ap_const_lv7_1;
        else 
            ap_phi_mux_indvars_iv1_phi_fu_155_p4 <= indvars_iv1_reg_152;
        end if; 
    end process;


    ap_phi_mux_n_phi_fu_166_p4_assign_proc : process(ap_CS_fsm_state1, n_reg_163, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_n_phi_fu_166_p4 <= ap_const_lv7_0;
        else 
            ap_phi_mux_n_phi_fu_166_p4 <= n_reg_163;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    arr_1_address0 <= zext_ln24_fu_188_p1(5 - 1 downto 0);

    arr_1_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arr_1_ce0 <= ap_const_logic_1;
        else 
            arr_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_1_d0 <= in_stream_TDATA;

    arr_1_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, empty_fu_174_p1, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_fu_174_p1 = ap_const_lv2_1))) then 
            arr_1_we0 <= ap_const_logic_1;
        else 
            arr_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_2_address0 <= zext_ln24_fu_188_p1(5 - 1 downto 0);

    arr_2_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arr_2_ce0 <= ap_const_logic_1;
        else 
            arr_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_2_d0 <= in_stream_TDATA;

    arr_2_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, empty_fu_174_p1, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_fu_174_p1 = ap_const_lv2_2))) then 
            arr_2_we0 <= ap_const_logic_1;
        else 
            arr_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_3_address0 <= zext_ln24_fu_188_p1(5 - 1 downto 0);

    arr_3_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arr_3_ce0 <= ap_const_logic_1;
        else 
            arr_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_3_d0 <= in_stream_TDATA;

    arr_3_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, empty_fu_174_p1, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_fu_174_p1 = ap_const_lv2_3))) then 
            arr_3_we0 <= ap_const_logic_1;
        else 
            arr_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_address0 <= zext_ln24_fu_188_p1(5 - 1 downto 0);

    arr_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arr_ce0 <= ap_const_logic_1;
        else 
            arr_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr_d0 <= in_stream_TDATA;

    arr_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, empty_fu_174_p1, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (empty_fu_174_p1 = ap_const_lv2_0))) then 
            arr_we0 <= ap_const_logic_1;
        else 
            arr_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_174_p1 <= ap_phi_mux_n_phi_fu_166_p4(2 - 1 downto 0);
    icmp_ln34_fu_220_p2 <= "1" when (unsigned(add_ln33_fu_208_p2) < unsigned(ap_const_lv7_64)) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    indvars_iv1_out <= ap_phi_mux_indvars_iv1_phi_fu_155_p4;

    indvars_iv1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, and_ln34_fu_226_p2, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_lv1_0 = and_ln34_fu_226_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            indvars_iv1_out_ap_vld <= ap_const_logic_1;
        else 
            indvars_iv1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_178_p4 <= ap_phi_mux_n_phi_fu_166_p4(6 downto 2);
    n_out <= ap_phi_mux_n_phi_fu_166_p4;

    n_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, and_ln34_fu_226_p2, ap_start_int)
    begin
        if ((not(((in_stream_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_lv1_0 = and_ln34_fu_226_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            n_out_ap_vld <= ap_const_logic_1;
        else 
            n_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln34_fu_214_p2 <= (in_stream_TLAST xor ap_const_lv1_1);
    zext_ln24_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_178_p4),64));
end behav;
