// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="alu_led_alu_led,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.473900,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=69,HLS_SYN_LUT=147,HLS_VERSION=2023_1}" *)

module alu_led (
        ap_clk,
        ap_rst,
        sw,
        led
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input  [7:0] sw;
output  [7:0] led;

wire   [2:0] num1_fu_78_p1;
reg   [2:0] num1_reg_172;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] num2_fu_82_p4;
reg   [2:0] num2_reg_180;
wire   [1:0] opcode_fu_92_p4;
reg   [1:0] opcode_reg_188;
wire   [0:0] icmp_ln25_fu_102_p2;
reg   [0:0] icmp_ln25_reg_192;
wire   [6:0] zext_ln11_1_fu_126_p1;
wire    ap_CS_fsm_state2;
wire  signed [6:0] sext_ln11_fu_142_p1;
wire   [6:0] zext_ln11_fu_158_p1;
reg   [6:0] ap_phi_mux_result_1_phi_fu_65_p10;
reg   [6:0] result_1_reg_61;
wire   [6:0] zext_ln11_2_fu_162_p1;
wire    ap_CS_fsm_state8;
wire   [2:0] grp_fu_108_p0;
wire   [2:0] grp_fu_108_p1;
wire   [2:0] result_3_fu_120_p0;
wire   [2:0] result_3_fu_120_p1;
wire   [5:0] result_3_fu_120_p2;
wire   [3:0] zext_ln19_fu_130_p1;
wire   [3:0] zext_ln19_1_fu_133_p1;
wire   [3:0] result_2_fu_136_p2;
wire   [3:0] zext_ln16_1_fu_149_p1;
wire   [3:0] zext_ln16_fu_146_p1;
wire   [3:0] result_fu_152_p2;
wire   [2:0] grp_fu_108_p2;
reg    grp_fu_108_ap_start;
wire    grp_fu_108_ap_done;
reg   [7:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire   [5:0] result_3_fu_120_p00;
wire   [5:0] result_3_fu_120_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

alu_led_udiv_3ns_3ns_3_7_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
udiv_3ns_3ns_3_7_seq_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_108_ap_start),
    .done(grp_fu_108_ap_done),
    .din0(grp_fu_108_p0),
    .din1(grp_fu_108_p1),
    .ce(1'b1),
    .dout(grp_fu_108_p2)
);

alu_led_mul_3ns_3ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 6 ))
mul_3ns_3ns_6_1_1_U2(
    .din0(result_3_fu_120_p0),
    .din1(result_3_fu_120_p1),
    .dout(result_3_fu_120_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_fu_102_p2 == 1'd1) & (opcode_fu_92_p4 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        result_1_reg_61 <= 7'd0;
    end else if (((icmp_ln25_reg_192 == 1'd0) & (opcode_reg_188 == 2'd3) & (1'b1 == ap_CS_fsm_state8))) begin
        result_1_reg_61 <= zext_ln11_2_fu_162_p1;
    end else if (((opcode_reg_188 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        result_1_reg_61 <= zext_ln11_fu_158_p1;
    end else if (((opcode_reg_188 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        result_1_reg_61 <= sext_ln11_fu_142_p1;
    end else if (((opcode_reg_188 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        result_1_reg_61 <= zext_ln11_1_fu_126_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((opcode_fu_92_p4 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln25_reg_192 <= icmp_ln25_fu_102_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        num1_reg_172 <= num1_fu_78_p1;
        num2_reg_180 <= {{sw[5:3]}};
        opcode_reg_188 <= {{sw[7:6]}};
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln25_reg_192 == 1'd0) & (opcode_reg_188 == 2'd3) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_result_1_phi_fu_65_p10 = zext_ln11_2_fu_162_p1;
    end else begin
        ap_phi_mux_result_1_phi_fu_65_p10 = result_1_reg_61;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_102_p2 == 1'd0) & (opcode_fu_92_p4 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_108_ap_start = 1'b1;
    end else begin
        grp_fu_108_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln25_fu_102_p2 == 1'd1) & (opcode_fu_92_p4 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((icmp_ln25_fu_102_p2 == 1'd0) & (opcode_fu_92_p4 == 2'd3) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign grp_fu_108_p0 = sw[2:0];

assign grp_fu_108_p1 = {{sw[5:3]}};

assign icmp_ln25_fu_102_p2 = ((num2_fu_82_p4 == 3'd0) ? 1'b1 : 1'b0);

assign led = $signed(ap_phi_mux_result_1_phi_fu_65_p10);

assign num1_fu_78_p1 = sw[2:0];

assign num2_fu_82_p4 = {{sw[5:3]}};

assign opcode_fu_92_p4 = {{sw[7:6]}};

assign result_2_fu_136_p2 = (zext_ln19_fu_130_p1 - zext_ln19_1_fu_133_p1);

assign result_3_fu_120_p0 = result_3_fu_120_p00;

assign result_3_fu_120_p00 = num2_reg_180;

assign result_3_fu_120_p1 = result_3_fu_120_p10;

assign result_3_fu_120_p10 = num1_reg_172;

assign result_fu_152_p2 = (zext_ln16_1_fu_149_p1 + zext_ln16_fu_146_p1);

assign sext_ln11_fu_142_p1 = $signed(result_2_fu_136_p2);

assign zext_ln11_1_fu_126_p1 = result_3_fu_120_p2;

assign zext_ln11_2_fu_162_p1 = grp_fu_108_p2;

assign zext_ln11_fu_158_p1 = result_fu_152_p2;

assign zext_ln16_1_fu_149_p1 = num2_reg_180;

assign zext_ln16_fu_146_p1 = num1_reg_172;

assign zext_ln19_1_fu_133_p1 = num2_reg_180;

assign zext_ln19_fu_130_p1 = num1_reg_172;

endmodule //alu_led
