-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MATMUL_MATMUL_Pipeline_load_A is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_TVALID : IN STD_LOGIC;
    A_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_15_ce0 : OUT STD_LOGIC;
    A_15_we0 : OUT STD_LOGIC;
    A_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_14_ce0 : OUT STD_LOGIC;
    A_14_we0 : OUT STD_LOGIC;
    A_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_13_ce0 : OUT STD_LOGIC;
    A_13_we0 : OUT STD_LOGIC;
    A_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_12_ce0 : OUT STD_LOGIC;
    A_12_we0 : OUT STD_LOGIC;
    A_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_11_ce0 : OUT STD_LOGIC;
    A_11_we0 : OUT STD_LOGIC;
    A_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_10_ce0 : OUT STD_LOGIC;
    A_10_we0 : OUT STD_LOGIC;
    A_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_9_ce0 : OUT STD_LOGIC;
    A_9_we0 : OUT STD_LOGIC;
    A_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_8_ce0 : OUT STD_LOGIC;
    A_8_we0 : OUT STD_LOGIC;
    A_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_7_ce0 : OUT STD_LOGIC;
    A_7_we0 : OUT STD_LOGIC;
    A_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_6_ce0 : OUT STD_LOGIC;
    A_6_we0 : OUT STD_LOGIC;
    A_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_5_ce0 : OUT STD_LOGIC;
    A_5_we0 : OUT STD_LOGIC;
    A_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_4_ce0 : OUT STD_LOGIC;
    A_4_we0 : OUT STD_LOGIC;
    A_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_3_ce0 : OUT STD_LOGIC;
    A_3_we0 : OUT STD_LOGIC;
    A_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_we0 : OUT STD_LOGIC;
    A_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_we0 : OUT STD_LOGIC;
    A_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_we0 : OUT STD_LOGIC;
    A_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_axis_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    s_axis_TREADY : OUT STD_LOGIC;
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axis_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of MATMUL_MATMUL_Pipeline_load_A is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln26_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal s_axis_TDATA_blk_n : STD_LOGIC;
    signal zext_ln26_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_142 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln26_fu_380_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_337 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component MATMUL_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component MATMUL_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_337)) then
                if ((icmp_ln26_fu_374_p2 = ap_const_lv1_0)) then 
                    i_fu_142 <= add_ln26_fu_380_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_142 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_10_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_10_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_10_ce0 <= ap_const_logic_1;
        else 
            A_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_10_d0 <= s_axis_TDATA(351 downto 320);

    A_10_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_10_we0 <= ap_const_logic_1;
        else 
            A_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_11_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_11_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_11_ce0 <= ap_const_logic_1;
        else 
            A_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_11_d0 <= s_axis_TDATA(383 downto 352);

    A_11_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_11_we0 <= ap_const_logic_1;
        else 
            A_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_12_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_12_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_12_ce0 <= ap_const_logic_1;
        else 
            A_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_12_d0 <= s_axis_TDATA(415 downto 384);

    A_12_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_12_we0 <= ap_const_logic_1;
        else 
            A_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_13_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_13_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_13_ce0 <= ap_const_logic_1;
        else 
            A_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_13_d0 <= s_axis_TDATA(447 downto 416);

    A_13_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_13_we0 <= ap_const_logic_1;
        else 
            A_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_14_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_14_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_14_ce0 <= ap_const_logic_1;
        else 
            A_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_14_d0 <= s_axis_TDATA(479 downto 448);

    A_14_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_14_we0 <= ap_const_logic_1;
        else 
            A_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_15_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_15_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_15_ce0 <= ap_const_logic_1;
        else 
            A_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_15_d0 <= s_axis_TDATA(511 downto 480);

    A_15_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_15_we0 <= ap_const_logic_1;
        else 
            A_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_1_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_1_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_1_ce0 <= ap_const_logic_1;
        else 
            A_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_1_d0 <= s_axis_TDATA(63 downto 32);

    A_1_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_1_we0 <= ap_const_logic_1;
        else 
            A_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_2_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_2_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_2_ce0 <= ap_const_logic_1;
        else 
            A_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_2_d0 <= s_axis_TDATA(95 downto 64);

    A_2_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_2_we0 <= ap_const_logic_1;
        else 
            A_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_3_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_3_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_3_ce0 <= ap_const_logic_1;
        else 
            A_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_3_d0 <= s_axis_TDATA(127 downto 96);

    A_3_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_3_we0 <= ap_const_logic_1;
        else 
            A_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_4_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_4_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_4_ce0 <= ap_const_logic_1;
        else 
            A_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_4_d0 <= s_axis_TDATA(159 downto 128);

    A_4_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_4_we0 <= ap_const_logic_1;
        else 
            A_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_5_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_5_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_5_ce0 <= ap_const_logic_1;
        else 
            A_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_5_d0 <= s_axis_TDATA(191 downto 160);

    A_5_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_5_we0 <= ap_const_logic_1;
        else 
            A_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_6_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_6_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_6_ce0 <= ap_const_logic_1;
        else 
            A_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_6_d0 <= s_axis_TDATA(223 downto 192);

    A_6_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_6_we0 <= ap_const_logic_1;
        else 
            A_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_7_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_7_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_7_ce0 <= ap_const_logic_1;
        else 
            A_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_7_d0 <= s_axis_TDATA(255 downto 224);

    A_7_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_7_we0 <= ap_const_logic_1;
        else 
            A_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_8_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_8_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_8_ce0 <= ap_const_logic_1;
        else 
            A_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_8_d0 <= s_axis_TDATA(287 downto 256);

    A_8_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_8_we0 <= ap_const_logic_1;
        else 
            A_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_9_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_9_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_9_ce0 <= ap_const_logic_1;
        else 
            A_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_9_d0 <= s_axis_TDATA(319 downto 288);

    A_9_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_9_we0 <= ap_const_logic_1;
        else 
            A_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    A_address0 <= zext_ln26_fu_386_p1(4 - 1 downto 0);

    A_ce0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_ce0 <= ap_const_logic_1;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_d0 <= s_axis_TDATA(32 - 1 downto 0);

    A_we0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_we0 <= ap_const_logic_1;
        else 
            A_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln26_fu_380_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_337_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
                ap_condition_337 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_state1, i_fu_142, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_142;
        end if; 
    end process;

    icmp_ln26_fu_374_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv5_10) else "0";

    s_axis_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_TDATA_blk_n <= s_axis_TVALID;
        else 
            s_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_TREADY_assign_proc : process(ap_CS_fsm_state1, s_axis_TVALID, icmp_ln26_fu_374_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (s_axis_TVALID = ap_const_logic_0)))) and (icmp_ln26_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_TREADY <= ap_const_logic_1;
        else 
            s_axis_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln26_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_3),64));
end behav;
