// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="insertion_sort_axis_insertion_sort_axis,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.700600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=349,HLS_SYN_LUT=1045,HLS_VERSION=2023_1}" *)

module insertion_sort_axis (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [0:0] icmp_ln39_fu_254_p2;
reg   [0:0] icmp_ln39_reg_389;
wire    ap_CS_fsm_state4;
wire   [6:0] add_ln39_1_fu_278_p2;
reg   [6:0] add_ln39_1_reg_413;
wire    ap_CS_fsm_state5;
wire   [1:0] trunc_ln39_fu_284_p1;
reg   [1:0] trunc_ln39_reg_418;
wire   [0:0] icmp_ln39_1_fu_273_p2;
wire   [31:0] key_fu_306_p6;
reg   [31:0] key_reg_443;
wire    ap_CS_fsm_state6;
reg   [4:0] arr_address0;
reg    arr_ce0;
reg    arr_we0;
reg   [31:0] arr_d0;
wire   [31:0] arr_q0;
reg   [4:0] arr_1_address0;
reg    arr_1_ce0;
reg    arr_1_we0;
reg   [31:0] arr_1_d0;
wire   [31:0] arr_1_q0;
reg   [4:0] arr_2_address0;
reg    arr_2_ce0;
reg    arr_2_we0;
reg   [31:0] arr_2_d0;
wire   [31:0] arr_2_q0;
reg   [4:0] arr_3_address0;
reg    arr_3_ce0;
reg    arr_3_we0;
reg   [31:0] arr_3_d0;
wire   [31:0] arr_3_q0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_idle;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_ready;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0;
wire   [6:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out_ap_vld;
wire   [6:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out_ap_vld;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_idle;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_ready;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TREADY;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TDATA;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID;
wire   [3:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TKEEP;
wire   [3:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TSTRB;
wire   [0:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TLAST;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_idle;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_ready;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0;
wire   [4:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0;
wire   [31:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0;
wire   [6:0] grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out;
wire    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out_ap_vld;
reg    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [6:0] indvars_iv1_loc_fu_94;
reg   [6:0] n_loc_fu_90;
reg    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [6:0] j_loc_fu_86;
wire   [63:0] zext_ln39_fu_298_p1;
wire   [63:0] zext_ln47_fu_342_p1;
wire    ap_CS_fsm_state9;
reg   [6:0] indvars_iv82_fu_114;
reg   [6:0] i_fu_118;
wire   [6:0] add_ln39_fu_350_p2;
wire   [1:0] trunc_ln47_fu_322_p1;
wire   [4:0] lshr_ln1_fu_288_p4;
wire   [6:0] add_ln47_fu_326_p2;
wire   [4:0] lshr_ln3_fu_332_p4;
wire    ap_CS_fsm_state11;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg = 1'b0;
#0 grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg = 1'b0;
#0 grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg = 1'b0;
end

insertion_sort_axis_arr_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
arr_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(arr_address0),
    .ce0(arr_ce0),
    .we0(arr_we0),
    .d0(arr_d0),
    .q0(arr_q0)
);

insertion_sort_axis_arr_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
arr_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(arr_1_address0),
    .ce0(arr_1_ce0),
    .we0(arr_1_we0),
    .d0(arr_1_d0),
    .q0(arr_1_q0)
);

insertion_sort_axis_arr_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
arr_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(arr_2_address0),
    .ce0(arr_2_ce0),
    .we0(arr_2_we0),
    .d0(arr_2_d0),
    .q0(arr_2_q0)
);

insertion_sort_axis_arr_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
arr_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(arr_3_address0),
    .ce0(arr_3_ce0),
    .we0(arr_3_we0),
    .d0(arr_3_d0),
    .q0(arr_3_q0)
);

insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1 grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start),
    .ap_done(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done),
    .ap_idle(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_idle),
    .ap_ready(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .arr_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0),
    .arr_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0),
    .arr_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0),
    .arr_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0),
    .arr_1_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0),
    .arr_1_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0),
    .arr_1_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0),
    .arr_1_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0),
    .arr_2_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0),
    .arr_2_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0),
    .arr_2_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0),
    .arr_2_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0),
    .arr_3_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0),
    .arr_3_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0),
    .arr_3_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0),
    .arr_3_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0),
    .indvars_iv1_out(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out),
    .indvars_iv1_out_ap_vld(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out_ap_vld),
    .n_out(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out),
    .n_out_ap_vld(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out_ap_vld)
);

insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4 grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start),
    .ap_done(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done),
    .ap_idle(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_idle),
    .ap_ready(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_ready),
    .out_stream_TREADY(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TREADY),
    .indvars_iv1_reload(indvars_iv1_loc_fu_94),
    .arr_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0),
    .arr_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0),
    .arr_q0(arr_q0),
    .arr_1_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0),
    .arr_1_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0),
    .arr_1_q0(arr_1_q0),
    .arr_2_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0),
    .arr_2_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0),
    .arr_2_q0(arr_2_q0),
    .arr_3_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0),
    .arr_3_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0),
    .arr_3_q0(arr_3_q0),
    .n_reload(n_loc_fu_90),
    .out_stream_TDATA(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TDATA),
    .out_stream_TVALID(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID),
    .out_stream_TKEEP(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TKEEP),
    .out_stream_TSTRB(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TSTRB),
    .out_stream_TLAST(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TLAST)
);

insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3 grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start),
    .ap_done(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done),
    .ap_idle(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_idle),
    .ap_ready(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_ready),
    .zext_ln39(indvars_iv82_fu_114),
    .arr_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0),
    .arr_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0),
    .arr_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0),
    .arr_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0),
    .arr_q0(arr_q0),
    .arr_1_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0),
    .arr_1_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0),
    .arr_1_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0),
    .arr_1_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0),
    .arr_1_q0(arr_1_q0),
    .arr_2_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0),
    .arr_2_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0),
    .arr_2_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0),
    .arr_2_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0),
    .arr_2_q0(arr_2_q0),
    .arr_3_address0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0),
    .arr_3_ce0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0),
    .arr_3_we0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0),
    .arr_3_d0(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0),
    .arr_3_q0(arr_3_q0),
    .key(key_reg_443),
    .j_out(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out),
    .j_out_ap_vld(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out_ap_vld)
);

insertion_sort_axis_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

insertion_sort_axis_mux_4_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_4_2_32_1_1_U31(
    .din0(arr_q0),
    .din1(arr_1_q0),
    .din2(arr_2_q0),
    .din3(arr_3_q0),
    .din4(trunc_ln39_reg_418),
    .dout(key_fu_306_p6)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TDATA),
    .vld_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TKEEP),
    .vld_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TSTRB),
    .vld_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

insertion_sort_axis_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TLAST),
    .vld_in(grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg <= 1'b1;
        end else if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_ready == 1'b1)) begin
            grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_ready == 1'b1)) begin
            grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln39_1_fu_273_p2 == 1'd1) | (icmp_ln39_reg_389 == 1'd1)))) begin
            grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_ready == 1'b1)) begin
            grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_254_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_118 <= 7'd1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_fu_118 <= add_ln39_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_254_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        indvars_iv82_fu_114 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        indvars_iv82_fu_114 <= add_ln39_1_reg_413;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        add_ln39_1_reg_413 <= add_ln39_1_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln39_reg_389 <= icmp_ln39_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out_ap_vld == 1'b1))) begin
        indvars_iv1_loc_fu_94 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_indvars_iv1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        j_loc_fu_86 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_j_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        key_reg_443 <= key_fu_306_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out_ap_vld == 1'b1))) begin
        n_loc_fu_90 <= grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_n_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        trunc_ln39_reg_418 <= trunc_ln39_fu_284_p1;
    end
end

always @ (*) begin
    if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_1_address0 = zext_ln47_fu_342_p1;
    end else if (((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        arr_1_address0 = zext_ln39_fu_298_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_1_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_1_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_1_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_address0;
    end else begin
        arr_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        arr_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_1_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_1_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_1_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_ce0;
    end else begin
        arr_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_1_d0 = key_reg_443;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_1_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_1_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_d0;
    end else begin
        arr_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln47_fu_322_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        arr_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_1_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_1_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_1_we0;
    end else begin
        arr_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_2_address0 = zext_ln47_fu_342_p1;
    end else if (((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        arr_2_address0 = zext_ln39_fu_298_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_2_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_2_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_2_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_address0;
    end else begin
        arr_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        arr_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_2_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_2_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_2_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_ce0;
    end else begin
        arr_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_2_d0 = key_reg_443;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_2_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_2_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_d0;
    end else begin
        arr_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln47_fu_322_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        arr_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_2_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_2_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_2_we0;
    end else begin
        arr_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_3_address0 = zext_ln47_fu_342_p1;
    end else if (((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        arr_3_address0 = zext_ln39_fu_298_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_3_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_3_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_3_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_address0;
    end else begin
        arr_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        arr_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_3_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_3_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_3_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_ce0;
    end else begin
        arr_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_3_d0 = key_reg_443;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_3_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_3_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_d0;
    end else begin
        arr_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln47_fu_322_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state9))) begin
        arr_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_3_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_3_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_3_we0;
    end else begin
        arr_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_address0 = zext_ln47_fu_342_p1;
    end else if (((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        arr_address0 = zext_ln39_fu_298_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_address0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_address0;
    end else begin
        arr_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln39_1_fu_273_p2 == 1'd0) & (icmp_ln39_reg_389 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        arr_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        arr_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_arr_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_ce0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_ce0;
    end else begin
        arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        arr_d0 = key_reg_443;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_d0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_d0;
    end else begin
        arr_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln47_fu_322_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state9))) begin
        arr_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        arr_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_arr_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_we0 = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_arr_we0;
    end else begin
        arr_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((icmp_ln39_1_fu_273_p2 == 1'd1) | (icmp_ln39_reg_389 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_1_fu_278_p2 = (indvars_iv82_fu_114 + 7'd1);

assign add_ln39_fu_350_p2 = (i_fu_118 + 7'd1);

assign add_ln47_fu_326_p2 = (j_loc_fu_86 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_31_1_fu_198_ap_start_reg;

assign grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3_fu_234_ap_start_reg;

assign grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_ap_start_reg;

assign grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state10);

assign icmp_ln39_1_fu_273_p2 = ((indvars_iv82_fu_114 == n_loc_fu_90) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_254_p2 = ((n_loc_fu_90 == 7'd0) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign lshr_ln1_fu_288_p4 = {{i_fu_118[6:2]}};

assign lshr_ln3_fu_332_p4 = {{add_ln47_fu_326_p2[6:2]}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_insertion_sort_axis_Pipeline_VITIS_LOOP_53_4_fu_216_out_stream_TVALID;

assign trunc_ln39_fu_284_p1 = i_fu_118[1:0];

assign trunc_ln47_fu_322_p1 = j_loc_fu_86[1:0];

assign zext_ln39_fu_298_p1 = lshr_ln1_fu_288_p4;

assign zext_ln47_fu_342_p1 = lshr_ln3_fu_332_p4;


reg find_kernel_block = 0;
// synthesis translate_off
`include "insertion_sort_axis_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //insertion_sort_axis

