// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln39,
        arr_address0,
        arr_ce0,
        arr_we0,
        arr_d0,
        arr_q0,
        arr_1_address0,
        arr_1_ce0,
        arr_1_we0,
        arr_1_d0,
        arr_1_q0,
        arr_2_address0,
        arr_2_ce0,
        arr_2_we0,
        arr_2_d0,
        arr_2_q0,
        arr_3_address0,
        arr_3_ce0,
        arr_3_we0,
        arr_3_d0,
        arr_3_q0,
        key,
        j_out,
        j_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] zext_ln39;
output  [4:0] arr_address0;
output   arr_ce0;
output   arr_we0;
output  [31:0] arr_d0;
input  [31:0] arr_q0;
output  [4:0] arr_1_address0;
output   arr_1_ce0;
output   arr_1_we0;
output  [31:0] arr_1_d0;
input  [31:0] arr_1_q0;
output  [4:0] arr_2_address0;
output   arr_2_ce0;
output   arr_2_we0;
output  [31:0] arr_2_d0;
input  [31:0] arr_2_q0;
output  [4:0] arr_3_address0;
output   arr_3_ce0;
output   arr_3_we0;
output  [31:0] arr_3_d0;
input  [31:0] arr_3_q0;
input  [31:0] key;
output  [6:0] j_out;
output   j_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] arr_address0;
reg arr_ce0;
reg arr_we0;
reg[4:0] arr_1_address0;
reg arr_1_ce0;
reg arr_1_we0;
reg[4:0] arr_2_address0;
reg arr_2_ce0;
reg arr_2_we0;
reg[4:0] arr_3_address0;
reg arr_3_ce0;
reg arr_3_we0;
reg j_out_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] j_1_reg_276;
wire    ap_CS_fsm_state2;
wire   [6:0] empty_fu_179_p1;
reg   [6:0] empty_reg_282;
reg   [0:0] tmp_1_reg_288;
wire   [1:0] empty_19_fu_209_p1;
reg   [1:0] empty_19_reg_312;
wire    ap_CS_fsm_state3;
wire   [31:0] tmp_fu_212_p6;
reg   [31:0] tmp_reg_316;
wire   [0:0] icmp_ln43_fu_226_p2;
reg   [0:0] icmp_ln43_reg_324;
wire   [63:0] zext_ln41_fu_201_p1;
wire   [63:0] zext_ln44_fu_246_p1;
wire    ap_CS_fsm_state4;
reg   [7:0] j_fu_60;
wire   [7:0] add_ln45_fu_254_p2;
wire   [7:0] zext_ln39_cast_fu_167_p1;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [4:0] lshr_ln2_fu_191_p4;
wire   [1:0] tmp_fu_212_p5;
wire   [6:0] add_ln44_fu_231_p2;
wire   [4:0] lshr_ln5_fu_236_p4;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

insertion_sort_axis_mux_4_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_4_2_32_1_1_U11(
    .din0(arr_q0),
    .din1(arr_1_q0),
    .din2(arr_2_q0),
    .din3(arr_3_q0),
    .din4(tmp_fu_212_p5),
    .dout(tmp_fu_212_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_60 <= zext_ln39_cast_fu_167_p1;
    end else if (((icmp_ln43_reg_324 == 1'd1) & (tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        j_fu_60 <= add_ln45_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        empty_19_reg_312 <= empty_19_fu_209_p1;
        icmp_ln43_reg_324 <= icmp_ln43_fu_226_p2;
        tmp_reg_316 <= tmp_fu_212_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_reg_282 <= empty_fu_179_p1;
        j_1_reg_276 <= j_fu_60;
        tmp_1_reg_288 <= j_fu_60[32'd7];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        arr_1_address0 = zext_ln44_fu_246_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        arr_1_address0 = zext_ln41_fu_201_p1;
    end else begin
        arr_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4))) begin
        arr_1_ce0 = 1'b1;
    end else begin
        arr_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_reg_324 == 1'd1) & (empty_19_reg_312 == 2'd0) & (tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        arr_1_we0 = 1'b1;
    end else begin
        arr_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        arr_2_address0 = zext_ln44_fu_246_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        arr_2_address0 = zext_ln41_fu_201_p1;
    end else begin
        arr_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4))) begin
        arr_2_ce0 = 1'b1;
    end else begin
        arr_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_reg_324 == 1'd1) & (empty_19_reg_312 == 2'd1) & (tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        arr_2_we0 = 1'b1;
    end else begin
        arr_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        arr_3_address0 = zext_ln44_fu_246_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        arr_3_address0 = zext_ln41_fu_201_p1;
    end else begin
        arr_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4))) begin
        arr_3_ce0 = 1'b1;
    end else begin
        arr_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_reg_324 == 1'd1) & (empty_19_reg_312 == 2'd2) & (tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        arr_3_we0 = 1'b1;
    end else begin
        arr_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        arr_address0 = zext_ln44_fu_246_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        arr_address0 = zext_ln41_fu_201_p1;
    end else begin
        arr_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4))) begin
        arr_ce0 = 1'b1;
    end else begin
        arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_reg_324 == 1'd1) & (empty_19_reg_312 == 2'd3) & (tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        arr_we0 = 1'b1;
    end else begin
        arr_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        j_out_ap_vld = 1'b1;
    end else begin
        j_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln43_fu_226_p2 == 1'd1) & (tmp_1_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((tmp_1_reg_288 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln44_fu_231_p2 = (empty_reg_282 + 7'd1);

assign add_ln45_fu_254_p2 = ($signed(j_1_reg_276) + $signed(8'd255));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign arr_1_d0 = tmp_reg_316;

assign arr_2_d0 = tmp_reg_316;

assign arr_3_d0 = tmp_reg_316;

assign arr_d0 = tmp_reg_316;

assign empty_19_fu_209_p1 = j_1_reg_276[1:0];

assign empty_fu_179_p1 = j_fu_60[6:0];

assign icmp_ln43_fu_226_p2 = (($signed(tmp_fu_212_p6) > $signed(key)) ? 1'b1 : 1'b0);

assign j_out = empty_reg_282;

assign lshr_ln2_fu_191_p4 = {{j_fu_60[6:2]}};

assign lshr_ln5_fu_236_p4 = {{add_ln44_fu_231_p2[6:2]}};

assign tmp_fu_212_p5 = j_1_reg_276[1:0];

assign zext_ln39_cast_fu_167_p1 = zext_ln39;

assign zext_ln41_fu_201_p1 = lshr_ln2_fu_191_p4;

assign zext_ln44_fu_246_p1 = lshr_ln5_fu_236_p4;

endmodule //insertion_sort_axis_insertion_sort_axis_Pipeline_VITIS_LOOP_43_3
